### ISSUE TITLE
Artifact Hub notifications URL point to localhost:8000

### ISSUE THREAD

**Issue by Vad1mo** [artifacthub/hub#1041]
The url in the email and the button point to http://localhost:8000/packages/helm/prometheus-community/kube-prometheus-stack/13.2.1 instead of https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/13.2.1

![image](https://user-images.githubusercontent.com/1492007/105674826-5ec00c00-5ee8-11eb-974d-764915de2963.png)

**Comment by tegioz** [comment]
Hi @Vad1mo 

That notification you've received was triggered by me by mistake while running a test this morning, that's why the url is pointing to the wrong host. Sorry about that. That package was actually updated 3 days ago and you should have received the same email with the correct host.

Thanks for reporting this, and sorry again for the inconvenience.

**Comment by Vad1mo** [comment]
true, thank you for the update
