### ISSUE TITLE
No docs/feedback that artifacthub-repo.yml in Helm chart repo isn't processed until index.yaml change

### ISSUE THREAD

**Issue by consideRatio** [artifacthub/hub#1045]
Thanks for your work on this project! :heart:

## Potential bug

1. A helm chart repo is defined on https://artifactshub.io.
   ![image](https://user-images.githubusercontent.com/3837114/105742131-68bf2a80-5f3b-11eb-960e-228b6833a40b.png)
2. A artifacthub-repo.yml file is exposed by the helm chart repo webserver on the same path level as index.yaml as demonstrated by the links below. This file contain a `repositoryID` matching the registered helm chart repo on artifactshub.io.
   - https://jupyterhub.github.io/helm-chart/index.yaml
   - https://jupyterhub.github.io/helm-chart/artifacthub-repo.yml
3. Yet there is no indication that we the artifactshub.io repo is to be considered a verified publisher, neither does it seem to have honored the ignored versions.
4. Note that the artifacthub-repo.yml file was added after the first import.

## Questions
- Is this a bug or a configuration error on my end?
- Are there any additional way I can debug this?

**Comment by tegioz** [comment]
Hi @consideRatio 👋 

I've just run a quick test locally and your `artifacthub-repo.yml` file seems to be fine. The package `binderhub` is not available and the `Verified publisher` badge is there, so nothing wrong on your end 🙂 

<img width="2056" alt="Screen Shot 2021-01-25 at 19 19 46" src="https://user-images.githubusercontent.com/1213902/105748701-c9059a80-5f42-11eb-9762-55edf8a5a9ac.png">

Please keep in mind that a repository is **not** processed if it hasn't changed since the last time it was tracked. For Helm repositories, we consider it has changed if the `index.yaml` file has changed. Is it possible that you've added the `artifacthub-repo.yml` file *after* it was processed the last time? We definitely need to improve this or at least document it 😅

**Comment by consideRatio** [comment]
> Is it possible that you've added the artifacthub-repo.yml file after it was processed the last time? We definitely need to improve this or at least document it :sweat_smile:

Ahhhhhhhhhhhh! That explains it, thank you!! I updated this topic to reflect the lack of docs/feedback about this behavior.

**Comment by tegioz** [comment]
No worries. Thanks, we'll address this soon 👍

**Comment by consideRatio** [comment]
@tegioz thank you for your help and work on this project!! ❤️

**Comment by tegioz** [comment]
No worries, my pleasure 😊
