### ISSUE TITLE
Generate resource names based on the Helm installation

### ISSUE THREAD

**Issue by alexrashed** [artifacthub/hub#1069]
Hi again!

We now have a full-fledged internal ArtifactHub instance running for our internal repositories. Thanks again for providing this software as open source!
In our environment we automated the setup using pipelines on out internal CI/CD server.
I would like to have the possibility to dynamically create staging / review environments for each change in our operations repo.
Unfortunately the Helm chart of Aritfactory currently uses hard-coded resource names (f.e. "hub" for the ArtifactHub's deployment resource name).
I would like to suggest to use a resource name based on the Helm installation (like the boilerplate chart created with `helm create <chart-name>`).
This would allow us to dynamically create multiple instances of ArtifactHub in a single Kubernetes namespace.
Using a single namespace for multiple installations doesn't only simplify the pipelines, but it would also allow us to clone the volume from production for our staging / review environments (volume cloning is only supported within a namespace with most CSI volume plugins).

Since this would change the current resource names for all resources in the Helm chart, I wanted to discuss this first.
Are there any restrictions, and would this be considered a breaking change?

I would provide a PR if the idea gets "approved". 😃

**Comment by tegioz** [comment]
Hi @alexrashed!

This is definitely a good idea, but you're right in thinking that it may be a bit of a breaking change 😅

Maybe we can work out a solution that allows for this dynamic prefix or suffix in resources names **optionally**, so that we don't cause any problems to existing installations. If it's an *opt-in* solution and by default the resource names stay the same it'd be easier to merge without the concern of breaking existing deployments.
