### ISSUE TITLE
Claim ownership of an existing org

### ISSUE THREAD

**Issue by beltran-rubo** [artifacthub/hub#1084]
Hi, I'm part of the Bitnami team and we would like to claim the ownership and get the 'verified publisher'. We already added the artifacthub-repo.yml file to the repository (with my user & email, the same ones that I configured in artifacthub) and it is publicly available but the Org already exists and it is not possible to claim it. Could you point me if I did anything wrong? Thanks

**Comment by tegioz** [comment]
Hi @beltran-rubo 👋 

At the moment it's not possible to claim the ownership of an organization, just repositories. Just in case it helps, the only member of the Bitnami organization appears in the list of owners you provided in the `artifacthub-repo.yml`. That member can easily invite the rest of you from the control panel. Given that you appear as an owner at the moment, you could also claim it transferring to your user account or another organization you belong to. But I think it may be easier if you keep the organization as it is and invite the rest of the members. Going that way, you don't really need the owners section in the metadata file.

Regarding the verified publisher flag, once you belong to the organization owning it, you can switch to its context in the control panel. In the repositories tab, you'll be able to see the repository id. Please use that one in your `artifacthub-repo.yml` file instead of `bitnami` (it's a UUID). The next time the repository is processed you'll obtain the badge 🙂

**Comment by beltran-rubo** [comment]
Thanks for the info! I will follow your suggestion.

**Comment by tegioz** [comment]
Awesome, no worries 👍
