### ISSUE TITLE
[OFFICIAL] consul

### ISSUE THREAD

**Issue by david-yu** [artifacthub/hub#1099]
*In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by *all* the packages available in the repository. When this status is granted for a repository, all packages available on it will display the `official` badge.*

- **Repository name** *(in `artifacthub.io`)*: hashicorp
- **Project URL:** https://artifacthub.io/packages/helm/hashicorp/consul
- **Source code URL** *(if available)*: https://github.com/hashicorp/consul-helm
- **Other relevant URLs:** 
    - https://github.com/hashicorp/consul
    - https://github.com/hashicorp/consul-k8s
    - https://www.consul.io/docs/k8s/installation/install 
    
**Before submitting this request, please confirm that your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The repository *only* contains `official` packages. A mix of official and non-official packages is not allowed at the moment, but we are considering to allow the `official` status to be set [at the package level](https://github.com/artifacthub/hub/issues/972) and this might change in the future.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] The packages available in the repository provide some documentation, usually in the form of a `README.md` file.

**Comment by tegioz** [comment]
Hi @david-yu 👋 

I've just checked and that repository belongs to the Helm organization. Would you mind [claiming its ownership](https://artifacthub.io/docs/topics/repositories/#ownership-claim) and get the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status? You can create a Hashicorp corporation and transfer the repo to it if you'd like ;) 

Please let me know if you run into any trouble.
Thanks!

**Comment by david-yu** [comment]
Appreciate the heads up, we'll look into this!

**Comment by david-yu** [comment]
Closing for now while we work on verified publisher status.

**Comment by david-yu** [comment]
Hi @tegioz reopening now since we are now a verified publisher!

**Comment by david-yu** [comment]
I assume this issue also addresses Vault as well since we are technically using the same Helm repo: https://helm.releases.hashicorp.com

**Comment by tegioz** [comment]
Official status ready!

Just in case you didn't know, Artifact Hub supports some [special annotations](https://artifacthub.io/docs/topics/annotations/helm/) that can improve users experience in some cases 🙂

**Comment by tegioz** [comment]
Hi @david-yu 👋 

I've just noticed that you have published some `beta` versions for your Consul chart (I haven't check the other charts in your repo). 

<img width="2007" alt="Screen Shot 2021-04-26 at 18 18 23" src="https://user-images.githubusercontent.com/1213902/116116884-f259d200-a6bb-11eb-88a9-5712a4c1029f.png">

<img width="2007" alt="Screen Shot 2021-04-26 at 18 18 33" src="https://user-images.githubusercontent.com/1213902/116116896-f5ed5900-a6bb-11eb-8956-60c87957d8cf.png">

This is fine, but I just wanted to let you know that Artifact Hub will offer users to install the latest version available from the installation modal, even if it's a beta version. If that's what you are intending to do, then everything is all right 🙂 

Otherwise, you have two options:

- You can [ignore packages matching certain patters from your repository metadata file](https://github.com/artifacthub/hub/blob/20c6540ae16feb7035ba0429fb45b0f0c8a105d4/docs/metadata/artifacthub-repo.yml#L18-L21). This way, `beta` packages won't even be visible in Artifact Hub.

- You can mark the package as `pre-release` using the [artifacthub.io/prerelease annotation](https://artifacthub.io/docs/topics/annotations/helm/). In this case, the `beta` version will be available but users will be warned that this is a pre-release version both in the installation modal and in the package view.

Hope this helps.-

**Comment by david-yu** [comment]
@tegioz Thank you! We were not aware of this and I will bring this up with the team to discuss options on this, as the beta release is meant only for non-production use cases.

**Comment by tegioz** [comment]
Awesome, no worries 👍
