### ISSUE TITLE
Search too specific

### ISSUE THREAD

**Issue by kfox1111** [artifacthub/hub#1101]
**Describe the bug**
Searching does not expose all the options due to how it splits up words

**To Reproduce**
Search for "gitlab-runner"

You will see packages related to gitlab-runners. You do not see gitlab-runner-operator* related packages, which are used to deploy gitlab-runners. You have to search manually for "gitlab-runner-operator" to see these. This greatly limits discoverability of related packages.

**Expected behavior**
gitlab-runner-* stuff should also be included in the search.

**Comment by tegioz** [comment]
Hi @kfox1111 👋 

When we process a package, its metadata (title, description, etc) is tokenized and each part is assigned a certain weight based on where it appeared. When something like `gitlab-runner` is found, both the full version (`gitlab-runner`) and each of the parts separated by the hyphens (`gitlab`, `runner`) are considered tokens.

In this particular case, IMHO the search is too specific because the search term was very specific. You asked for the packages containing the `gitlab-runner` token by using the hyphen between both words, and it was only found in the following results:

<img width="2084" alt="Screen Shot 2021-02-09 at 08 35 13" src="https://user-images.githubusercontent.com/1213902/107330373-c1510480-6ab1-11eb-9bf5-563ef5bdc28b.png">

However, without the hyphen, which would look to me a more natural search (`gitlab runner`), I think it yields the results you were expecting originally:

<img width="2084" alt="Screen Shot 2021-02-09 at 08 36 22" src="https://user-images.githubusercontent.com/1213902/107330498-eba2c200-6ab1-11eb-892a-2cf6cebe9421.png">

You can also search for `gitlab runner operator` and it will show the appropriate results:

<img width="2084" alt="Screen Shot 2021-02-09 at 08 40 12" src="https://user-images.githubusercontent.com/1213902/107330969-8c917d00-6ab2-11eb-9266-91533596dae6.png">

Similarly, the related packages displayed at the bottom of the right column on the package view seem to be producing good results as well in this case, as the operators are shown as related to the gitlab runners packages.

<img width="367" alt="Screen Shot 2021-02-09 at 08 56 40" src="https://user-images.githubusercontent.com/1213902/107332672-bfd50b80-6ab4-11eb-9360-cf7454eabe7a.png">

I don't really think this is a bug, as it's actually working as intended. The ability to search for those specific terms creates more possibilities, and you always have the flexibility of using a less specific search term. IMHO I think most users wouldn't use the hyphen in that kind of search, but if it's a concern for the case of the operator you are publishing, we have some options 🙂

May I suggest you add a `gitlab-runner` keyword to your operator? That will make sure it is displayed when someone searches using that exact term. If there are more interesting related keywords you can think of, they definitely help positioning your package better both in search results and related packages searches. And if you use some that match the words that appear in the categories filter (`integration` in this case, for example), your package will also show up when users exploring packages filter by that category.

Hope this helps.
Thanks!

**Comment by tegioz** [comment]
Related to #1080

**Comment by kfox1111** [comment]
Ok. I'll add the keyword. Thanks!

**Comment by tegioz** [comment]
Awesome, no worries! 👍
