### ISSUE TITLE
Repo stuck after error occurred in fetching Index.

### ISSUE THREAD

**Issue by HoustonPutman** [artifacthub/hub#1180]
Hello, I have an issue concerning the "Apache Solr" repository.

**Describe the bug**
Our helm chart (https://solr.apache.org/charts) is a redirect to the actual location of the helm chart. This works fine using helm locally, and worked with artifactHub for about a week. On March 11th, there was an error fetching the index file for the helm repo. We can see the following "tracking error logs"
```
error getting repository remote digest: Get "https://solr.apache.org/charts/index.yaml": read tcp 192.168.85.221:46836->95.216.26.30:443: read: connection reset by peer
```

I thought this would go away after the next cycle, but it persists. I have checked the URL, and it does work. I also changed the repo URL in artifactHub to be the location it redirects to (https://nightlies.apache.org/solr/helm-charts/), however ArtifactHub still keeps the same error message. This makes me think that it hasn't actually retried since getting the error 4 days ago. There is no way that the error could be the same when I have changed the repo URL.

**Comment by tegioz** [comment]
Hi @HoustonPutman 

Can you confirm if the index.yaml file has changed since that error happened? When the tracker starts processing repositories, it first does a quick check to verify if the repo has been updated since the last time it was processed. In the case of Helm repositories, it checks if that file has been modified. And if it hasn't, the repo is skipped and revisited again in 30 mins.

The tracking errors are not updated until the repository is processed again (skipped ones are not updated). If this is the case, they should go away as soon as the repository is updated (new version published, updated, etc). On the other hand, if the repo has been updated in the last few days (index.yaml updated), please let me know and I'll gladly check what's going on 🙂

**Comment by HoustonPutman** [comment]
The index.yaml file has not changed since that error, so that makes sense.

Thanks for clearing that up!

**Comment by tegioz** [comment]
Awesome, no worries 👍
