### ISSUE TITLE
Provide stats on a per-repo/per-package level

### ISSUE THREAD

**Issue by tomkerkhove** [artifacthub/hub#1246]
**Is your feature request related to a problem? Please describe.**
I'm trying to get more insights into the adoption of the products that we publish.

**Describe the solution you'd like**
Provide stats on a per-repo/per-package level for publishers to understand the adoption of their artifacts.

**Describe alternatives you've considered**
Doing it on every artifact repository, but [Artifact Hub Stats](https://artifacthub.io/stats) motivated me to have everything in one place.

**Additional context**
N/A

**Comment by tegioz** [comment]
Hi @tomkerkhove 

We would love to be able to track and display some stats at the package level, like downloads, for example. The problem is that, unfortunately, we don't know when a package is downloaded as we don't host the artifacts. They are downloaded directly from the original repository.

We could consider tracking packages' pages views if users think it can be useful, but it's a tricky subject and we could easily get skewed numbers that may not be very useful.

We have the `stars`, which require users to be logged in, and hopefully as Artifact Hub gets more traction we'll see numbers go up. We also allow users to **subscribe to new releases notifications** for any package (and eventually there'll be more events), so we could display this number in the package view as well (I've just checked and we have ~800 subscriptions across all packages vs the ~2.5k stars). But somehow a subscription shows that a user is actively following your artifact, which may help understanding its adoption.

<img width="418" alt="Screen Shot 2021-04-14 at 10 13 09" src="https://user-images.githubusercontent.com/1213902/114676869-0986e000-9d0a-11eb-9921-190c8242e898.png">

**Comment by tomkerkhove** [comment]
Good point actually, I need more coffee :)

Sorry about this stupid suggestion, there's no way you can know the stats on the artifacts themselves.
