### ISSUE TITLE
ArtifactHub support for CoreDNS internal + external plug-ins

### ISSUE THREAD

**Issue by caniszczyk** [artifacthub/hub#1275]
I'd like to explore how we can support CoreDNS plug-ins

https://coredns.io/plugins/
https://coredns.io/explugins/

**Comment by tegioz** [comment]
Hi @caniszczyk 

This is mostly working, so if the CoreDNS team is happy with how this works I think it's ready to go 🙂 

<img width="2008" alt="coredns1" src="https://user-images.githubusercontent.com/1213902/116242393-28539080-a766-11eb-9229-5fe642af5dc5.png">

<img width="2008" alt="coredns2" src="https://user-images.githubusercontent.com/1213902/116242408-2b4e8100-a766-11eb-91d7-a89da0f7e0c9.png">

Current support for CoreDNS plugins is very similar to what we discussed recently for KEDA scalers (link to discussion for reference: https://github.com/artifacthub/hub/issues/1227#issuecomment-814827964).

Documentation on how to add a CoreDNS repository to Artifact Hub can be found [here](https://github.com/artifacthub/hub/blob/tegioz/coredns/docs/repositories.md#coredns-plugins-repositories). We've created a fork of the `coredns` repo to add the necessary [metadata files to each of the plugins](https://github.com/coredns/coredns/compare/master...tegioz:tegioz/artifacthub), just for testing. They could use it as a starting point or we can create a PR, whatever works best for them. This should allow to add the `in-tree` plugins repository easily to Artifact Hub. Other publishers would be able to add more CoreDNS plugins repositories as usual.

There are a couple of details that they may want to check:

- `Version`: packages in AH require a version, not sure how they want to deal with this exactly. For testing, we've set all of them to `1.0.0`. Artifact Hub supports multiple versions for any package, if they wish to do it that way. They can also only support one, it's up to them. If they opt for only supporting one, the version or the package's digest should change so that we can pick up the changes.

- `CreatedAt`: packages should also provide a creation timestamp. For now we've set it to today's date.

The rest of the fields should be OK. More details about the Artifact Hub package metadata format can be found [here](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml).

Please let us know if you have any feedback or questions.

**Comment by chrisohaver** [comment]
Cool!  I definitely see this working for external plugins.  For _internal_ plugins, I'm still chewing on it.

**Comment by tegioz** [comment]
Awesome! We'll go ahead and merge then, thanks 👍

**Comment by tegioz** [comment]
Support for CoreDNS plugins has been deployed to production 🙂 

We've added the fork we created yesterday to `staging` so that you can [see how it would look like in action](https://staging.artifacthub.io/packages/search?page=1&kind=9). We can remove it from staging if you'd like, it's not a problem.

For external plugins, in the simplest scenario, publishers would only need to add an Artifact Hub metadata file to their repo and add the repo to Artifact Hub from the UI control panel. You can find an example of an external plugin repo ready for Artifact Hub [here](https://github.com/tegioz/coredns-git/tree/tegioz/artifacthub). For more complex setups, please check the [repositories guide](https://artifacthub.io/docs/topics/repositories/#coredns-plugins-repositories) and the [package metadata spec](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml).

If you decide to also add the internal plugins to Artifact Hub, the widgets feature may come in handy to display them in your website (demo: https://jsfiddle.net/0cye2zwk/).

<img width="1137" alt="Screen Shot 2021-04-28 at 10 45 52" src="https://user-images.githubusercontent.com/1213902/116374841-f64a3900-a80e-11eb-9dfd-600443b3a498.png">
