### ISSUE TITLE
error preparing package: gzip: invalid header

### ISSUE THREAD

**Issue by callumeveratt** [artifacthub/hub#1321]
Hey,

I'm trying to set up my helm repo on the artifact hub, I've uploaded a quick Helm Chart to test and I can see the scanner is getting the correct details but fails to download / read the tgz.

> error preparing package: error loading chart (https://helm.avacon.co.uk/charts/kube-scan-0.0.2.tgz): gzip: invalid header (package: kube-scan version: 0.0.2)

The chart was packaged with helm package and the index created with helm index, I can run helm fetch and successfully grab the package.

I can guarantee this will likely be config of my webserver or something, but I was wondering if there was an easy solution to this or anyone had seen it before?

Thanks!

**Comment by tegioz** [comment]
Hi @callumeveratt 👋 

I think the issue is that your server is setting the `content-encoding` header to `gzip` in the response, when maybe it shouldn't for this kind of file. This is causing the http client we use to uncompress it automatically, so when we try to process it as if it was compressed, the error you got is raised.

Said this, I think we can solve it in our end as this might happen again in the future. We are going to explicitly set the `Accept-Encoding` header to `gzip` in the request used to fetch the chart archive. This way the response [shouldn't be automatically uncompressed](https://github.com/golang/go/blob/8b0901fd32aa9c29a1fa4ed8cd517914920a1509/src/net/http/transport.go#L187-L189). We could also disable the compression in the client's transport, but it's used to fetch other kind of content as well, so let's see first how this goes.

I'll get back to you soon 👍

**Comment by tegioz** [comment]
I think this should be fixed @callumeveratt, will deploy it a bit later today.

**Comment by callumeveratt** [comment]
@tegioz Awesome, thank you. If you let me know when I'll take a look :)

**Comment by tegioz** [comment]
Your package has been published: https://artifacthub.io/packages/helm/avacon/kube-scan 🙂 

It'd be great if you could add a readme file to it 😇

**Comment by callumeveratt** [comment]
Amazing, thank you for your help!

Going to tidy up and add readme etc now :) - wanted to get the base picked up first!

**Comment by tegioz** [comment]
Awesome! No worries 👍

There are also some [special annotations](https://artifacthub.io/docs/topics/annotations/helm/) that can help.
