### ISSUE TITLE
[OFFICIAL] Apache Airflow

### ISSUE THREAD

**Issue by kaxil** [artifacthub/hub#1327]
In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by a package. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/helm/apache-airflow/
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://airflow.apache.org/ | https://github.com/apache/airflow
- **Source code URL** *(if available)*: https://github.com/apache/airflow and chart is at https://github.com/apache/airflow/tree/master/chart
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*
  We just voted and released the Chart through ASF Voting guidelines as Airflow is the part of an Apache Software Foundation project. I am one of the release managers and PMC Member of the project.

Voting Email: https://lists.apache.org/thread.html/r865f041e491a2a7a52e17784abf0d0f2e35c3bac5ae8a05927285558%40%3Cdev.airflow.apache.org%3E
Release Announcement: https://lists.apache.org/thread.html/r131d839158b8a7a92a7813183cae30d248be9e330ea2faaf9e654970%40%3Cdev.airflow.apache.org%3E

I have added artifacthub-repo.yml ([commit](https://github.com/apache/airflow-site/commit/ddd1cacbca25f0ef23b830466275fa452c078dc8)) to http://airflow.apache.org/artifacthub-repo.yml but had provided our Dev email for the project: dev@airflow.apache.org -- hence it hasn't verified the Helm repo on artifacthub yet as my personal email is kaxilnaik@gmail.com. We (Airflow Committers) would like to use our dev list email (dev@airflow.apache.org) instead of any committer's personal email. Hope you can help with Verified Publisher as well.

Airflow Contributor's URL: https://github.com/apache/airflow/graphs/contributors

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ ] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Thanks @kaxil, everything looks good and the package has just been marked as `Official`.

Regarding the `Verified Publisher` flag, just adding the `repositoryID` to the metadata file is enough, as the owners email is only used to claim the repository's ownership at the moment. We set the verified publisher flag every time your repository is processed, but please note it won't be processed again unless something has changed since the last time it was processed. Maybe the `artifacthub-repo.yml` was added *after* the package had already been indexed. So until a new version is released (or the current one modified), it wouldn't be picked. I've tested it locally and the verified publisher flag was set fine, so I've applied it manually for you. Every time you publish a new release the metadata file will be checked again and the flag updated accordingly.

**Comment by kaxil** [comment]
Thank you very much @tegioz 🎉
