### ISSUE TITLE
False Security report for cert-manager 1.5.3

### ISSUE THREAD

**Issue by wallrj** [artifacthub/hub#1553]
The "Security Report" for https://artifacthub.io/packages/helm/cert-manager/cert-manager/1.5.3?modal=security-report displays Rating D and refers to such vulnerabilities as https://cve.circl.lu/cve/CVE-2010-0834 which seem to be Ubuntu specific.

![image](https://user-images.githubusercontent.com/978965/133614472-26cb6399-b92e-4fe9-8d65-994cad7b9764.png)

cert-manager uses `gcr.io/distroless/static` base image so I can't imagine that our images are vulnerable although they do appear to contain some  configuration files which might be part of the package covered by that CVE.

Also note that older cert-manager releases still show security rating A, despite using the same or older distroless base images

![image](https://user-images.githubusercontent.com/978965/133614605-79a6155a-57a2-4951-a0e6-182f8de98f4b.png)

**Comment by wallrj** [comment]
See 
 * https://github.com/GoogleContainerTools/distroless/issues/701

**Comment by tegioz** [comment]
Hi @wallrj 👋 

The security rating of `cert-manager` has been (automatically) updated back to `A` 🙂

It looks like the cause was an issue in the Trivy vulnerabilities database that was affecting Debian scans (aquasecurity/trivy-db#152) for a few hours, which was fixed quickly (aquasecurity/trivy-db#153).
