### ISSUE TITLE
Transfer Kubernetes and Kubernetes-SIGs organizations to the Kubernetes steering committee

### ISSUE THREAD

**Issue by dims** [artifacthub/hub#1684]
Following up on https://github.com/kubernetes/steering/issues/188

Here are the email ids of the folks on steering:
https://github.com/kubernetes/steering#top-level-accounts

I do have sc1@ already registered with artifacthub, so can you please transfer the two orgs to sc1 (we will register sc2 and sc3 as well soon):
- https://artifacthub.io/packages/search?org=kubernetes-sigs&sort=relevance&page=1
- https://artifacthub.io/packages/search?org=kubernetes&sort=relevance&page=1

Thanks!
Dims

**Comment by tegioz** [comment]
Hi @dims 👋 

At the moment both Kubernetes and Kubernetes-SIGs organizations have several members (related issue: https://github.com/kubernetes/org/issues/2587). Any of them can invite the **sc1-2-3** users to the corresponding organization from the Artifact Hub control panel. Once that's done they could leave the organization if you'd like to only have the **sc1-2-3** users control it. I think it's better to transfer the ownership in the open this way 🙂

I'll ping the current members so that they can be aware of the process and invite you.

**Kubernetes:** @scottrigby @aledbf @mattfarina @gjtempleton @cblecker
**Kubernetes-SIGs:** @scottrigby  @marquiz @chriskim06

Just in case it helps, Artifact Hub includes a [fine-grained authorization mechanism](https://artifacthub.io/docs/topics/authorization/) that allows organizations to define what actions can be performed by their members.

Please let me know if I can be of any help.

**Comment by mattfarina** [comment]
I've invited sc1 to the kubernetes org.

**Comment by dims** [comment]
thanks @mattfarina

**Comment by dims** [comment]
@scottrigby @marquiz @chriskim06 can you please invite me to the kubernetes-sigs org?

@tegioz not trying to take over :) just trying to make sure we are in here helping folks who are doing the work.

**Comment by scottrigby** [comment]
@mattfarina thanks for the ping 😄 

@dims Hi again 👋  I just added `sc1` Artifact Hub user as a member of `kubernetes-sigs` org there.

@tegioz thanks for tying back to https://github.com/kubernetes/org/issues/2587#issuecomment-804960783. Good to keep awareness of this for when it's time for these orgs to implement the fine-grained perms option ❤️ 

Just wanna take this opportunity to say it's so nice collaborating with y'all ✨

**Comment by dims** [comment]
@scottrigby thanks! accepted and moved two packages into it (extenal-dns and metrics-server)

**Comment by dims** [comment]
closing this now!

**Comment by mauriciopoppe** [comment]
hey @dims, do we have a process to publish verified helm packages to https://artifacthub.io/packages/search?org=kubernetes-sigs&sort=relevance&page=1? I saw a few verified packages that you pushed in https://github.com/artifacthub/hub/issues/1684#issuecomment-967464782 and we're trying to do the same in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/400
