### ISSUE TITLE
Configurable timeouts for webhooks

### ISSUE THREAD

**Issue by jmezach** [artifacthub/hub#1736]
**Is your feature request related to a problem? Please describe.**
We have a webhook setup for a couple of Helm charts that trigger an Azure Function app. Unfortunately it takes some time for the Azure Function app to startup so the webhook always runs into a timeout.

**Describe the solution you'd like**
It would be nice if we would be able to configure the timeout for the webhook so that it doesn't fail.

**Describe alternatives you've considered**
We could of course have our Azure Function app always running, but this kind of defeats the purpose of serverless. Especially since this is only called occasionally.

**Additional context**
In our case we are using Azure Functions, but I can imagine this would also happen with something similar on AWS or Google Cloud.

**Comment by tegioz** [comment]
Hi @jmezach 👋 

We've been thinking a bit about this a maybe we could try to increase the default timeouts. It's not a problem to make them configurable. However there are [some timeouts](https://github.com/artifacthub/hub/blob/1ce795f9145747b5f4de24590515b8831e7bcb46/internal/util/http.go#L35-L59) that may need adjusting depending on the scenario, and we'd rather not to expose too much complexity to users. Also, situations like this are likely to happen again as cold starts of serverless functions may take longer than the current timeouts, and it's probably better if it worked out of the box and users wouldn't have to investigate what's going on.

We'll let you know when it's deployed so that you can give it a try and check if this would solve your problem 🙂

Thanks!

**Comment by jmezach** [comment]
Totally agree with that, that would be even simpler. Looking forward to giving it a spin :).

**Comment by tegioz** [comment]
Deployed @jmezach 🚀

**Comment by jmezach** [comment]
I just tried this, but I still got an error while testing the webhook from the control panel. Not sure if that's the same thing though. We've only setup webhooks for a couple of Helm charts which haven't seen any updates yet since this was deployed so I can't yet verify that this works for the regular path.

**Comment by tegioz** [comment]
When testing from the control panel the [hub server write timeout](https://github.com/artifacthub/hub/blob/114eb52473fe092e2bf73815a5bf13cec702f1eb/cmd/hub/main.go#L86) applies, so the effective timeout in that case will be 30s, which may not be enough in your case. For the regular path, the 60s timeout should apply. Please let us know how it goes when you can verify it. Thanks!

**Comment by jmezach** [comment]
I'm glad to say that last night (at least for us ;)) we've successfully received a webhook from ArtifactHub on our Azure Function app and it didn't timeout on the ArtifactHub side. So it seems like this is working now.

**Comment by tegioz** [comment]
Awesome, thanks for letting us know @jmezach 👍
