### ISSUE TITLE
User moderation and additional information

### ISSUE THREAD

**Issue by jemag** [artifacthub/hub#1823]
**Is your feature request related to a problem? Please describe.**
Currently there seems to be a few users/publishers that produce an incredible amount of low value or duplicate charts. This can make for a more frustrating search experience and a bit harder to find the more official charts

**Describe the solution you'd like**
Provide a way to obtain detailed information about a user. Ideas:
- Contact information
- Organization
- Some kind of verification (e.g.: if user is officially part of that organization and this has been verified)
- etc.

Also, provide a way to moderate or report potential abusive users from publishing charts.

**Additional context**
I am providing this with the current example of user : joaquinito2051
This users has around 1323 duplicate of charts: https://artifacthub.io/packages/search?user=joaquinito2051&sort=relevance&page=1
With sometimes up to 13 of the same or similar chart : https://artifacthub.io/packages/search?user=joaquinito2051&ts_query_web=cert-manager&sort=relevance&page=1

Being able to obtain more information about a user could help people make more informed decision. Being able to moderate or have a "report user" feature could help prevent malicious users.

**Comment by tegioz** [comment]
Hi @jemag 👋 

Thanks for raising this issue. We've been discussing this a bit in #1653 (some thoughts [here](https://github.com/artifacthub/hub/issues/1653#issuecomment-951656650)).

It's a tricky problem as many times those users are just trying to help and make more packages available to other users. But I agree we should do our best to make the most relevant packages to stand out and help users make the best decision. We've added a number of features (like official and verified badges, stars, production users, release frequency, last update, views graphs, etc) to help with that and we'd love to keep adding more 🙂

**Comment by jemag** [comment]
Hi @tegioz 

I agree that good strides have already been made to better detect official and appropriate charts and it is good to keep adding more.

However, I guess my point was leaning a bit more in the opposite direction: have mechanisms to prevent chart spam and block malicious or exceedingly low value users.

What would happen if there were thousands of users like joaquinito2051 that duplicate almost a quarter of all the charts available? Or if there were malicious users that start spamming insecure versions of charts? 

While these could technically be handled manually, it might be good to have the community help out and be able to report (or block or vote against or any such moderation feature) such users.

**Comment by dmaciel** [comment]
I just found out this issue today, I was looking for a chart and I noticed seeing the 'joaquinito2051' user on a different search a few days ago. 

I don't know what are his intentions, but having one user with 1849 matches (https://artifacthub.io/packages/search?user=joaquinito2051&sort=relevance&page=1) while bigger orgs like Bitnami only have 96 items (https://artifacthub.io/packages/search?org=bitnami&sort=relevance&page=1) doesn't makes sense.

There should be a limit on the number of artifacts you should be able to publish based on your history or your status (official/verified). Even with good intentions there is no way one org/person is able to maintain so many charts. I know there are some communities doing it (k8s@home) but that should be the exception and no the rule

This issue was reported 2 months ago and the numbers of charts under that user has grown almost 40% (1323->1849). It is basically the biggest publisher, with more charts than the 'Helm' and 'Artifact Hub' organizations. It appears on the "Publisher" list on the left column that can make it look as a serious publisher like the others in the same list

I understand there is no easy solution, but this specific case is getting out of hand, probably removing the charts will break something, but it should be removed from all search results ASAP

**Comment by tegioz** [comment]
Hi @dmaciel @jemag 👋 

The publisher in Artifact Hub refers to the organization or user who listed the content in Artifact Hub, not the creator or maintainer of the content. The reason why `joaquinito2051` appears as the top publisher is because they have listed a lot (101 actually) of Helm charts repositories available on the Internet. Some of these repositories may provide duplicate or low value charts, indeed, but others may provide unique content and be quite useful.

You can find below a subset of the repositories listed by `joaquinito2051`:

```
                                url                                | subscriptions | stars | packages | views
-------------------------------------------------------------------+---------------+-------+----------+-------
 https://folio-org.github.io/folio-helm/                           |            14 |     1 |       85 |   322
 https://helm-charts.wikimedia.org/stable/                         |             6 |     8 |       53 |  1352
 https://openinfradev.github.io/helm-repo                          |             4 |     2 |       68 |  1026
 https://raw.githubusercontent.com/KvalitetsIT/helm-repo/master/   |             4 |     2 |       12 |   210
 https://spotinst.github.io/spotinst-kubernetes-helm-charts        |             4 |     2 |        1 |   144
 https://charts.fairwinds.com/incubator                            |             2 |     0 |       27 |   496
 https://mozilla-it.github.io/helm-charts/                         |             2 |     0 |       18 |   316
 https://witcom-gmbh.github.io/witcom-charts/                      |             2 |     0 |       13 |   116
 https://charts.wener.tech                                         |             1 |     8 |       80 |  3624
 https://cloudnativeapp.github.io/charts/curated/                  |             1 |     4 |      255 |  8920
 https://mesosphere.github.io/charts/stable                        |             1 |     0 |       38 |   649
 https://marketplace.azurecr.io/helm/v1/repo                       |             0 |     8 |      106 |  8370
 https://factly.github.io/helm-charts                              |             0 |     3 |       10 |   235
 https://jenkins-x-charts.github.io/v2/                            |             0 |     2 |       89 |  1778
 https://mesosphere.github.io/charts/staging                       |             0 |     1 |       26 |  1971
 https://inseefrlab.github.io/helm-charts-datascience              |             0 |     1 |       33 |  1147
 https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm |             0 |     1 |       24 |   897
 https://wenerme.github.io/charts                                  |             0 |     1 |       80 |   682
 https://bryanalves.github.io/helm-charts/                         |             0 |     1 |       19 |   483
 https://library-charts.k8s-at-home.com                            |             0 |     1 |        1 |   431
 https://charts.alexbabel.com/                                     |             0 |     1 |        7 |   391
 https://camptocamp.github.io/helm-geoserver-cloud                 |             0 |     1 |        4 |    99
 https://raw.githubusercontent.com/luiscajl/helm-charts/gh-pages   |             0 |     1 |       20 |    68
 https://statcan.github.io/charts                                  |             0 |     0 |       39 |  1278
 https://charts.opencord.org/                                      |             0 |     0 |      107 |   577
 https://redhat-cop.github.io/helm-charts                          |             0 |     0 |       23 |   568
 https://charts.openshift.io/                                      |             0 |     0 |       31 |   546
 https://camptocamp.github.io/charts                               |             0 |     0 |       68 |   537
 https://charts.cloudnativetoolkit.dev                             |             0 |     0 |       94 |   516
 https://charts.stakewise.io                                       |             0 |     0 |       20 |   479
```

IMHO I don't see any bad or abuse intentions here, probably the opposite: they're just collecting Helm charts repositories and making them more easily discoverable for other users. Blocking someone for that wouldn't probably be fair. And some users are interested in some of those repos as shown by the numbers above, so removing them doesn't feel right either.

Even though anyone can list any publicly available repository on Artifact Hub, there is a way for legit owners to [claim its ownership](https://artifacthub.io/docs/topics/repositories/#ownership-claim). If some of these repositories shouldn't be listed on AH for any reason, one way to fix this nicely would be to ask their legit owners to claim their ownership and disable them from the AH control panel. This will remove the content from AH and will prevent anyone else from adding that repository again in the future (repositories urls must be unique).

The `verified publisher` flag can also be of help. This flag indicates if the publisher of the repo actually owns it or has control over it. So users can easily filter out this content if they wish so. Maybe at some point this could be the default, like we do with deprecated, but I don't think we are there yet as a lot of good content would be left out in the search results by default.

Hope this helps 🙂

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
