### ISSUE TITLE
OLM bundles may appear on ArtifactHub before they are available from OperatorHub 

### ISSUE THREAD

**Issue by wallrj** [artifacthub/hub#1828]
A new (release-candidate) version of the cert-manager OLM package was merged yesterday:
 * https://github.com/k8s-operatorhub/community-operators/pull/780

But the Release to OperatorHub.io pipeline failed:
 * https://github.com/k8s-operatorhub/community-operators/issues/783

And now it is  appearing prematurely on ArtifactHub 
 * https://artifacthub.io/packages/olm/community-operators/cert-manager
![Screenshot from 2022-02-17 09-39-43](https://user-images.githubusercontent.com/978965/154450041-8ca091b1-3a8e-4cf8-8afb-aae9d19ff909.png)

With installation instructions which won't work until operatorhub.io is actually updated:

```console
$ curl -v https://operatorhub.io/install/candidate/cert-manager.yaml
*   Trying 23.200.147.105:443...
* Connected to operatorhub.io (23.200.147.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=North Carolina; L=Raleigh; O=Red Hat, Inc.; CN=prod1.redhat.com
*  start date: Jan  5 00:00:00 2022 GMT
*  expire date: Jan  4 23:59:59 2023 GMT
*  subjectAltName: host "operatorhub.io" matched cert's "operatorhub.io"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /install/candidate/cert-manager.yaml HTTP/1.1
> Host: operatorhub.io
> User-Agent: curl/7.76.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< x-powered-by: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 84
< ETag: W/"54-Rc1YPuUZ0wYYyqF3/bqi8PNTzjo"
< Date: Thu, 17 Feb 2022 09:50:52 GMT
< Connection: keep-alive
< Set-Cookie: 83a035de55728a3724f00c31df326b3b=05f40dc3e795ad32f82be29ceb9e0007; path=/; HttpOnly; Secure; SameSite=None
< 
* Connection #0 to host operatorhub.io left intact
Requested channel does not exists or there is no default channel in operator package
```

**Comment by tegioz** [comment]
Hi again! 

Artifact Hub does not check `operatorhub.io` when processing packages, the source of truth is the git repository containing the community operators. We provide those installation instructions as a convenience for users, but we don't check if they are online. We rely on git repositories (or OCI registries) because we support OLM operators repositories that may not be listed on `operatorhub.io`. In those cases a different set of installation instructions is displayed.

Somehow this problem may affect all package kinds if the original source is not available when users try to install a package (Helm charts repository can be down, etc). But I think when something like this happens, most of the time it will be clear for users what's going on.

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed.
