### ISSUE TITLE
OLM package installation page should show the "default" channel by default

### ISSUE THREAD

**Issue by wallrj** [artifacthub/hub#1829]
Stable releases of cert-manager OLM package have an annotation containing the name of the default channel:
 * https://github.com/k8s-operatorhub/community-operators/blob/50e434048ca5a1badf32772f92b3a7bbe17e6b04/operators/cert-manager/1.6.1/metadata/annotations.yaml#L8

But ArtifactHub shows the "candidate" channel by default:

![Screenshot from 2022-02-17 09-39-43](https://user-images.githubusercontent.com/978965/154455051-4aacef10-c843-458b-94d4-7840a72aac2c.png)

The default channel annotation is documented here:
 * https://olm.operatorframework.io/docs/best-practices/channel-naming/#defining-channels

And the actual behaviour of the OLM catalog tools with regard to the default channel is explained in:
 * https://github.com/operator-framework/operator-registry/issues/330#issuecomment-764734595

**Comment by tegioz** [comment]
Hi @wallrj 👋 

Thanks for raising this issue!

Quoting the [link you shared](https://github.com/operator-framework/operator-registry/issues/330#issuecomment-764734595):

> "it means that "the defaultChannel is taken from the defaultChannel value from the highest semver bundle" (and since it's optional, it's really from the highest semver bundle that has a defaultChannel value)

Artifact Hub is getting the default channel from the highest semver bundle, but NOT from the highest one that has a default value set. We had to do it this way due to how some things work internally in AH. In your case, the highest is `1.6.2-rc1` and that version doesn't have a default value set. What you are doing is correct, but if you could add the default channel annotation to the latest version AH should pick it up.

Once we can read the default channel correctly, the installation page should show it by default (IIRC that's already supported).

I'll review this a bit to see if we can match exactly that behavior though 👍

**Comment by wallrj** [comment]
I still don't think this is right.
I've just released cert-manager 1.6.2 stable to operatorhub.io and now ArtifactHub is showing it as in the candidate channel.

It is in both the stabls __and__ the candidate channels.
But the default channel has been set to stable.

![Screenshot from 2022-03-15 17-28-41](https://user-images.githubusercontent.com/978965/158436711-48cdf6b0-68df-430b-aa78-87dd3632ccb3.png)
