### ISSUE TITLE
[Feature] Add passage.id support for auth flow

### ISSUE THREAD

**Issue by caniszczyk** [artifacthub/hub#1851]
Lets catch up on this @tegioz but want to improve auth capabilities in artifacthub, from biometrics to MFA etc

https://passage.id

**Comment by tegioz** [comment]
Hi @caniszczyk 

Please note that Artifact Hub already supports 2FA. It can be enabled from the settings tab in the control panel, at the bottom of the profile. This feature is only available when you sign in using your email. Otherwise authentication is delegated to the external oauth provider, where the user can also have 2FA enabled.

As of today, ~10k out of the 12k registered users on `artifacthub.io` have signed in using Github or Google. Only 61 of those 2173 (less than 3%) have enabled 2FA so far. Maybe we could publicize a bit more this feature 🙂 

<img width="634" alt="Two-factor authentication" src="https://user-images.githubusercontent.com/1213902/158124268-4b064902-0026-482d-a7ad-7cb2a0f960e1.png">

**Comment by tegioz** [comment]
Will close this issue for now, please feel free to reopen it if needed 🙂
