### ISSUE TITLE
Falco artifacts source

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#220]
If we look at falco rules in the hub right now we can see a few things ([here's an example](https://artifacthub.io/package/admin-activities))...

- You can't see where the rule came from. There is no tie back to the Falco projects curated list
- The URL does not contain falco to know the type

For the rules coming from the Falco project can we get something to point people to that. Helm charts tell you the repo. Until then, the falco project asked we not list their rules so people don't think it's a divided/forked set.

**Comment by kris-nova** [comment]
Hi!

Just wonder why this is closed? The website `artifacthub.io` still seems to be scraping Falco rules from our [repositories](https://github.com/falcosecurity/cloud-native-security-hub). Furthermore, there doesn't seem to be any support/ownership for the rules you are offering.

Examples:

https://artifacthub.io/packages/search?page=1&text=falco

Can we please attach ownership to these unofficial rules, and label these as `unofficial` somehow?

**Comment by tegioz** [comment]
Hi Kris!

Please take a look at the first two comments in the PR (#227) which closed this ticket. I think the concerns/issues described originally in the ticket were addressed, that's why it was closed. In addition to those changes, when you hover over the organization name, some more details are now exposed as well.

About the `unofficial` label suggestion: given that it's now clear those rules belong to the Falco organization and the source url on each package details points directly to the Cloud Native Security Hub Github repo, don't you think that could be misleading for users?
