### ISSUE TITLE
show in sidebar: Security over time

### ISSUE THREAD

**Issue by hpvd** [artifacthub/hub#2442]
**Is your feature request related to a problem? Please describe.**

showing the results of the security scan in type of `Number of vulnerabilities` and its classification in the sidebar is great!
Since this is only a snapshot of today's state, it only tells half of the story.

A very large project may have more vulnerabilities than a small project, simply because of the higher number of lines of code.
And critical vulnerability may be just found yesterday...

What may complete the picture and would transport somehow the **importance of security within the project**, would be the development of the number of vulnerabilities over time.

**Describe the solution you'd like**
would be nice to have a small diagram in the sidebar **`Security over time`** which shows the development of the number of vulnerabilities of e.g. the last 6 month.
Similar to the diagram `Last 30 days views` (see attachment)

**Describe alternatives you've considered**
adding a small `arrow symbol` for rising and falling to the already shown number of vulnerabilities plus a number, e.g. `+18/6Month`

**Additional context**

![2022-10-24_14h42_36](https://user-images.githubusercontent.com/5681880/197531851-7db3863c-06f7-4995-ab55-0d395268aa67.png)

=> what do you think??

**Comment by tegioz** [comment]
Hi @hpvd 👋

Providing more security related information to users would be great, thanks!

I’m not sure right now how/if this would fit, so will share some thoughts to keep the discussion going and we’ll see where it takes us 🙂

At the moment, the security report summary displayed on the package view, refers to a *specific* version. If you switch to a different version on the top of that bar, you’ll be able to see the report for that particular version.

Given that any given version usually doesn’t change, its number of vulnerabilities only grows over time (AH continues scanning periodically previous versions that aren’t older than 1 year IIRC). So maybe illustrating this per version over time wouldn’t help much.

Users can now see the vulnerabilities evolution across versions (although not easily, they need to switch back and forth). But I'm not sure if trends in that evolution can be used to draw useful conclusions regarding security. IMHO often newer versions will have fewer vulnerabilities, and when this is not the case, it could be just due to new dependencies added that cannot be replaced, and not necessarily that the project isn't concerned about security.

It's a tricky subject and we need to make sure that any move really helps both users and publishers 😅

Maybe something we could do is to highlight somehow that a package has high severity well known (maybe more than 1 or 2 years old) and fixable vulnerabilities that haven't been addressed yet. This could help users decide if they'd like to use the package or not, and it could also be an incentive for projects to address those issues. Does this sound useful?

**Comment by hpvd** [comment]
Hi @tegioz 

Many thanks for your thoughts to this. You are absolutely right. The proposed solution was not the silver bullet, but anyway it drives the discussion to the IMHO pretty important direction of `security over time`  and the `importance of security ` in generell within a project :-)

I saw that there were the old versions shown, but I didn't get it, that this is the `main switch` and somehow a possibility to gather the information I'm looking for. Maybe it's only me or it's a UI thing (font/color/symbol...) ... Thanks for pointing to it!

I like your idea to show something using the knowledge about the fixability of vulnerabilities. On idea could be, showing the average duration from possible fix documented - till it is applied (CVE is gone).

**Comment by tegioz** [comment]
No worries, my pleasure! :)

> On idea could be, showing the average duration from possible fix documented - till it is applied (CVE is gone).

This would be nice, but unfortunately I think we don't have the dates when fixes are available. This is tricky as well, specially when vulnerabilities are detected in software installed using the OS package manager, as some distributions may release a fix sooner, and others not do it at all. But it's something interesting to keep in mind though 👍

The screenshot below illustrates my previous suggestion (which is BTW inspired on your comment in the issue you opened in the Apache Pulsar Helm chart repository, when you mentioned the 2013 vulnerability ;).

<img width="1305" alt="test" src="https://user-images.githubusercontent.com/1213902/197722971-be7bff0c-be1c-4903-bd58-a33583897d14.png">

**Comment by hpvd** [comment]
since you mentioned the pulsar helm chart... to be honest seeing its state of security this well-prepared and summarized at artifacthub, was a somehow shocking moment for me, because many things came together:
- the risk level of found vulnerabilities
- the pure number,
- the age 
- and the fact that most of them should be easily fixable..

-> so artifacthub did a stunning job! And a solution is on the go...

And yeah, your idea showing an extra warning help to drive attention into the right direction!

Looking at these points in this example again,
and looking into how the rating at artifact hub is determined today (depending on level of CVEs found)

=> maybe one can even think further?

can we find possibilities to show
A) a **different rating** for projects
- with 1 critical vulnerability found yesterday for the first time (today: F)
- vs with 10 critical vulnerabilities found 1 year ago (today: F)

B) a **more balanced rating** for
- 1 critical vulnerability found 2 years ago (today: F)
- vs 100 medium vulnerability found 2 years ago? (today: C)
since combining different vulnerabilities together may be more worth than looking at them alone...


Of course, there is no true objective way doing this... but maybe there is a good chance to make the rating even more fair and precise than it is today.

There are at least three things that may help (you have probably discussed them already...):

1) applying an **amplifying factor** to each level e.g. 1000 for critical, 100 high, 10 for medium 1 for low and 10 for unknown

2) multiplying it with the **number of findings**

3) adding a second rating for velocity of getting rid of fixable vulnerabilities (also containing the same amplifying factor...)

**Comment by tegioz** [comment]
> Of course, there is no true objective way doing this... but maybe there is a good chance to make the rating even more fair and precise than it is today.

I agree there is a lot of room to improve the rating in terms of accuracy and fairness. The current model is probably too simple and we're definitely open to change how it works if needed.

On the other hand, if a different mechanism was used, I think it's important that it allows us to explain in a quick and simple way what the rating means to *all* users. Some may use it to make quick decisions, and it's better if they don't have to trust an obscure value they don't know where it comes from. That's the reason why we opted for not making it more complex when this feature was added(*). In the end, for precision, they can always open the full report and judge by themselves if the risk is acceptable for their use case.

(*) In addition to realizing that it'd be hard, if not impossible, to have a correct outcome anyway. There are so many variables, like how a vulnerability actually affects a project (some may not at all), which ones affect only when using some feature, on some platform, OS, etc. Also, our intention was to encourage projects to fix critical and high severity vulnerabilities whenever possible, that's why we surface those so easily and let them make a poor final rating.

<img width="606" alt="rating" src="https://user-images.githubusercontent.com/1213902/197749543-8d033934-9786-4c79-996d-924e0ac1c025.png">

**Comment by tegioz** [comment]
> And yeah, your idea showing an extra warning help to drive attention into the right direction!

Awesome, we'll add it then ;)

**Comment by hpvd** [comment]
Totally agree with your arguments! They are all valid.  As mentioned, it's already doing a stunning job...

**Comment by hpvd** [comment]
last idea:

A triple A (A/A/A) may make every A perfectly easy understandable ;-)

1. A: worst vulnerability: same as today
2. A: total vulnerability: SUM number(all)*amplifying factor ("vulnerability surface" = nr*factor)
3. A: unfixed dept: total vulnerability / SUM number(fixable)*amplifying factor

**Comment by tegioz** [comment]
@cynthia-sg and I have given it a quick try but we're not sure this may be intuitive. We'll think a bit more about everything we've discussed to see if something else comes up 👍

Ideas are always welcome and it's always worth thinking a bit about them or even giving them a quick try, so don't hesitate sharing any of them! Many of the current features came up this way actually 🙂

<img width="393" alt="Screen Shot 2022-10-25 at 14 05 38" src="https://user-images.githubusercontent.com/1213902/197768997-bfb4076d-e072-47d9-9f6a-3a781d6d7f9d.png">
<img width="393" alt="Screen Shot 2022-10-25 at 14 05 45" src="https://user-images.githubusercontent.com/1213902/197769001-0f4b590e-88e7-41c6-84d2-3a3dec812d51.png">
<img width="393" alt="Screen Shot 2022-10-25 at 14 05 53" src="https://user-images.githubusercontent.com/1213902/197769005-e5518c1d-e489-401a-862a-905137f22d56.png">
<img width="393" alt="Screen Shot 2022-10-25 at 14 06 17" src="https://user-images.githubusercontent.com/1213902/197769007-5bdab3fe-8969-4e8c-9917-d87f620793c1.png">

**Comment by hpvd** [comment]
oh wow, many thanks for visualizing it. Yes you are right.. we have to think a little further to make it more intuitive.

Lessons learned: having 3 independent values making comparison of which image is better harder.
When wanting to run in this direction, one need something like
- a main value
- with maybe 3 sub values...
where the main value may be something like the average...

**Comment by tegioz** [comment]
The warning has been deployed to production, you can see it in action [here](https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report).

<img width="1539" alt="warning" src="https://user-images.githubusercontent.com/1213902/198647108-6e104301-5ebb-4a70-adaa-611140cd071e.png">

Will close this issue for now, thanks!
