### ISSUE TITLE
44 vulnerabilities (36 fixable) have been detected in this package's images

### ISSUE THREAD

**Issue by hpvd** [artifacthub/hub#2457]
**Describe the bug**
just looked at artifacthubs's latest helm chart (1.10.0) at artifacthub.io with your own tool:
You certify yourselves as having poor security :-)

https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=security-report

**Expected behavior**
first class security - since you have build the right tools to visualize security flaws and their solution and you may stumble over it on daily basis...

**Screenshots**
![2022-10-27_16h49_56](https://user-images.githubusercontent.com/5681880/198324261-c8860fc2-4654-4250-8471-2b80352103d3.png)

**Comment by hpvd** [comment]
could also be a great E2E test if your website is able to show `class A` and the color `green` :-D

**Comment by hpvd** [comment]
oach... looks like in main some/most updates are already included... so only a new helm chart has to be released...
which version are you using in live? the 1.10.0 from helmchart?

**Comment by tegioz** [comment]
Hi @hpvd 

No matter how often you cut new releases, there will always be a period in which some vulnerabilities are surfaced. We could indeed release more often, but it's important to find the right balance between all the tasks the project requires so that we can keep adding new features, fixing issues and working on other projects.

> You certify yourselves as having poor security :-)

We update all base images, backend and frontend dependencies on a weekly basis (as required). Sometimes this consumes more time one would expect, as we need to go through the changes and make sure everything works fine, it's not just updating some version numbers. So if we were only measuring security by this point (which we shouldn't), I wouldn't classify it as poor security. Public container images are built on each release, but `artifacthub.io` uses images built every new commit to master, so the latest updates are usually applied on a daily basis.

In addition to this, and regarding the rating, we rely on other software we don't have control over their release cycle. So even when everything is up to date on our side, we may still get an `F` because it's been a few days or weeks since one of our dependencies was released and some recent vulnerabilities have started showing up (sometimes it happens with the Trivy image). And IMHO this is fine and normal, and we like to be transparent about it and let users decide if that risk is acceptable for them.

Hope this helps 🙂
