### ISSUE TITLE
Preserve filter on search query change

### ISSUE THREAD

**Issue by marniks7** [artifacthub/hub#2631]
**Is your feature request related to a problem? Please describe.**
1. Trying to search among `Tekton Tasks` and only them (not interested in anything else)
2. Open https://artifacthub.io/packages/search?kind=7&ts_query_web=kubectl&sort=relevance&page=1
3. Change query from "kubectl" to "kube"
AR: Filter (by kind) is cleared and now I am searching among all artifacts

So I am forced to filter by "kind" once again... and again.
This is super inconvenient. I have come for tekton tasks, not helm charts or some other k8s resources.
And more over, I cannot give a direct link to the people, `https://artifacthub.io/packages/search?kind=7`, because after the search filter will gone.

**Describe the solution you'd like**
Preserve the filters, do not clear them at all on query search change.

**Describe alternatives you've considered**
* each time filter by `kind`
* search tekton tasks on github
* this one works as intended https://hub.tekton.dev/

**Comment by tegioz** [comment]
Hi @marniks7 👋

This is something we discussed some time ago when we started working on Artifact Hub, I understand what you mean.

The problem is that doing it the other way also had some drawbacks, it wasn't easy to pick 😅. When the filters are maintained across searches, it's possible to forget they are there, and subsequent searches may show only a subset of the expected results. This can be even more likely when users new to AH receive a link with filters and try a new search. In the end one of the goals of Artifact Hub was to help with discoverability, so we opted for the current behavior.

This indeed can be inconvenient in some use cases like yours, but the alternative could be inconvenient in other situations, as the filters would need to be manually cleared each time. I don't think there is a right or wrong answer for this. You will find some sites (like Amazon or the Docker Hub) that reset the filters on each search, and others that don't, like DuckDuckGo or the Python Package Index. And both approaches are fine IMHO.

We can leave this open and see what others think about it. At this point we need to be careful with this kind of change, as thousands of users use AH on a daily basis and many of them are probably used to the way it works. But if most users agree this is the way to go we'd be happy to change it, it's not a problem 🙂

Regarding not being able to give a direct link to people, you could search first and filter after, and the resulting url as displayed in the browser should be correct and ready to share. Otherwise please let us know and we'll gladly look into it.

**Comment by marniks7** [comment]
Hi @tegioz,

By sharing the link, I mean, I would like to share with my teammates this one https://artifacthub.io/packages/search?kind=7&kind=11 (with only Tekton-related kinds). If they go by that link and try to search - they will get unrelated results.

You are giving good examples, some thoughts:

- Amazon: In order to solve the problem of subsequent searches they have "Department" which they preserve
![image](https://user-images.githubusercontent.com/9289172/209400118-bb980714-ff54-4a7b-a249-32fa857fb9df.png)
- Docker: I would say that for `products` they need to do in similar way as Departments, but it may not be that important so far, as `plugins` is niche, IMHO, as for `extensions` there are only 33 so far (subsequent search is no use here)

So, I would say that preserving only `kind` (and moving them out of filter section) could be a good balance.

**Comment by tegioz** [comment]
Hi @marniks7

We've been discussing this a bit more but for now we think it's better to leave it working as it is. The main reason is that it could be counterproductive in facilitating discoverability, which is one the Artifact Hub main goals.

Thank you very much anyway!
