### ISSUE TITLE
 Add architectures filter

### ISSUE THREAD

**Issue by icefery** [artifacthub/hub#2681]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

- There seems to be no way to known whether the helm chart supports ARM except take a look at docker image on DockerHub. It might be very useful to add architectures filter like DockerHub.

- The UI image layout seems to be too tight, image information might be a little more important for helm chart.

**Describe alternatives you've considered**

No

**Additional context**

No

**Comment by tegioz** [comment]
Hi @icefery 👋

Displaying the architectures supported by the charts images would be great. We already do something similar for other package kinds, like [Tekton tasks](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/git-clone) (please see supported platforms in the right column).

The problem is that we don't have that information at the moment. Helm may eventually define an official way of declaring charts images (more info in [this issue](https://github.com/helm/helm/issues/7754)), where this information could fit well. In the meantime, we try to extract the containers images used by Helm charts from the manifests generated from a dry-run install using the default values. It's not a perfect solution, but it helps a bit. When the auto detection doesn't work or it's not accurate, publishers can provide the images via a special AH annotation ([artifacthub.io/images](https://artifacthub.io/docs/topics/annotations/helm/)) in the [Chart.yaml file](https://helm.sh/docs/topics/charts/#the-chartyaml-file).

One solution could be to extend the structure accepted by that annotation with a new field, maybe `platforms`, and display it when the publishers provide it. Unfortunately not many charts use that annotation, but it could be a start 🙂

Filtering at the chart level could be trickier though. Even if we had a properly defined list of all the images that a chart can use, including the platforms for each, depending on the charts' options used the chart might support a different set of platforms (as a different set of images and/or charts dependencies could be used). So in the case of a chart, unlike a single image, it may be a bit harder to say if it supports a given platform.

**Comment by tegioz** [comment]
Hi @icefery

Helm charts publishers can now provide the platforms supported on each of the images from the `artifacthub.io/images` annotation. When available, we'll display them as well on the UI 🙂

<img width="1352" alt="images-platforms" src="https://user-images.githubusercontent.com/1213902/214816441-c5fe2c6e-9ae4-4766-97ec-9565771778c7.png">
