### ISSUE TITLE
API: webhooks POST requests fail with error code 500

### ISSUE THREAD

**Issue by arldka** [artifacthub/hub#2694]
**Describe the bug**
POST requests for webhooks and org creation generate an error 500 and no error message

**To Reproduce**
1. Go to https://artifacthub.io/docs/api/#/Webhooks/addUserWebhook
2. Add the ApiKeyId and ApiKeySecret
3. Try to create the webhook
4. error 500

**Expected behavior**
The POST request should return an error message in the event of a server error and in the case of a correct request, should create the resource and return a 201 status code. 

**Screenshots**
![ah_1](https://user-images.githubusercontent.com/43825600/214041103-e74c2a34-fbc2-46f7-b1c4-e4e9fcf91f7a.png)
![ah_2](https://user-images.githubusercontent.com/43825600/214041115-a160ea00-792f-4cf1-b180-ccac0c560c7c.png)
![ah_3](https://user-images.githubusercontent.com/43825600/214041131-75f00bb1-4f4e-42c1-b4c0-c2534a4a26f9.png)

**Comment by tegioz** [comment]
Hi @arldka 👋 

It looks like the problem is the package id used, which doesn't exist in the database, it's just an example for the docs.

We usually try to provide some error message when the request fails for some known reasons. But in other cases, specially with some errors coming from the database, sometimes we hide them to avoid exposing certain internal details. I agree in this case it'd have been helpful though, so we'll try to improve it 🙂

When setting up a webhook, we need to provide what will trigger it, which must be a certain event on any of the packages provided. Please see the screenshot below from the control panel in the UI as it illustrates some of the options available (it uses the same API endpoint to create it):

<img width="1453" alt="webhook" src="https://user-images.githubusercontent.com/1213902/214076335-c8a2c07e-5743-425f-86a1-a8aaac090616.png">

Hope this helps!

**Comment by arldka** [comment]
Hi @tegioz,

I can't believe I've been racking my brain with the wrong input from the beginning :sweat_smile: !

Maybe it would be useful to use the artifact-hub package_id in the examples ?

Thank you !

**Comment by tegioz** [comment]
No worries!

I don't think we have added that sample id ourselves, maybe it was something automatic from Swagger (we declare that field as `uuid`). But we'll double check anyway, thanks!
