### ISSUE TITLE
[OFFICIAL] ClusterSecret

### ISSUE THREAD

**Issue by zakkg3** [artifacthub/hub#3078]
Hi. Here we go with the official ClusterSecret artifact :)

- **Repository name** *(in `artifacthub.io`)*:  CluterSecret
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://charts.clustersecret.io/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** NO
- **Source code URL** *(if available)*: https://github.com/zakkg3/ClusterSecret
- **Other relevant URLs:** https://clustersecret.io/
**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ x ] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [ x ] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [ x ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @zakkg3 👋

It looks like your Helm repo contains two very similar packages. Could you please just leave one of them?

I see that the one named `ClusterSecret` has a newer version and the README file, so that one is ready to go. However, the name used in the other one (`cluster-secret`) has the advantage of being easier to discover when users search for `cluster secret`. So whatever works best for you 🙂

FYI the repo is named `CluterSecret`, with a missing `s` in `Cluster`, not sure if that was intentional.

<img width="1482" alt="Screenshot 2023-05-26 at 08 31 20" src="https://github.com/artifacthub/hub/assets/1213902/05927cc3-ac43-4b5d-9f14-9160c7127e49">

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
