### ISSUE TITLE
Contributions to Infra

### ISSUE THREAD

**Issue by kris-nova** [artifacthub/hub#311]
Hi - how does one gain access to the backend infrastructure of this project?

 - Where is it hosted? 
 - Can I contribute?
 - How does one get involved with the hosting?

**Comment by mattfarina** [comment]
These are some good questions. I can try to answer the questions here.

> how does one gain access to the backend infrastructure of this project?

Become a maintainer on the project. Since there is a datastore with login credentials and other info, access to the infra is restricted and will likely remain that way. The other part of the infra is CI which is GitHub Actions so that is covered and changes there are just a PR away.

We could look at adding an infra team to manage the infra but it's not that heavyweight of a task. While I've not done the work to figure out the time here I can speak to managing the similarly sized infra for the Helm Hub where I did work it out. There is averages out to minutes a month.

> Where is it hosted?

The site itself is hosted using Kubernetes running in Amazon for the app. RDS for the database.

As of yet there are no images or cut releases. We are planning on getting to those.

> Can I contribute?

Yes. But, we don't really need help with the running site. The areas we could use more help is being able to self host and run this yourself. There are some things that could easily be contributed:

* We need built images in a public accessible location. I'm not sure if Docker Hub or Quay would be a better location. Something to work out. But, CI (via GitHub Actions) pushing images to a Hub (or the Hub pulling and building) is something we should do.
* The Helm chart could use improvements. It and the CI process around it should be broken out so the chart is far more well documented and generic (maybe a new Git repo) and the what is used for artifacthub.io is separate.

If you or someone else wanted to start working on those bits it would be fantastic.

**Comment by tegioz** [comment]
I'll close this one for now, please reopen if needed. Some of the points mentioned in Matt's reply have already been addressed though.
