### ISSUE TITLE
[OFFICIAL] eximiait

### ISSUE THREAD

**Issue by mbecca** [artifacthub/hub#3188]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: eximiait (https://artifacthub.io/packages/search?repo=eximiait)
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://github.com/eximiait/charts
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** none
- **Source code URL** *(if available)*: https://github.com/eximiait/charts
- **Other relevant URLs:**

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @mbecca 👋

I'm not sure if the official status applies to this case. For a package named openshift* to be marked as official, it should probably be published by RedHat. Something similar kind of happens with the one that refers to Redis Insight.

Hope this makes sense 🙂

**Comment by mbecca** [comment]
Hello, @tegioz .

I perfectly understand what you are explaining. Let me detail a bit about how these packages/artifacts we want to formalize work and what their objective is.

The main goal of both is to facilitate the integration of any application (for example, redis-insight) with OpenShift/OKD's OAuth. I understand that both OpenShift and redis-insight are products/solutions external to our repository (eximiait), but what we want is to simplify and facilitate such integration for the community.

I hope this is clear! And thanks again for your response. 😀

Please let me know if you need more details.

**Comment by tegioz** [comment]
Hi @mbecca

Thanks for the explanation! I understand, and it looks great 🙂

The official status main goal is to give users some extra information to help them decide about using a package or not. If they see a package named openshift* marked as official, they may easily think that it comes from RedHat, which can be misleading. So in cases like this in which the name of another product or organization appears in the package name, we usually can't process the request unfortunately. But we do it this way only with the intention of continuing helping users 😇

**Comment by mbecca** [comment]
Hi @tegioz 

Thanks again for the response, I have one last question for you:
Would it suffice if we modify the name to okd* (OKD is the open source version of OpenShift) or will it not be possible to formalize these types of packages at all?

Thank you and best regards.

**Comment by tegioz** [comment]
The problem would be the same unfortunately, it's not because it's a commercial product. The point is that these packages are focused on some software that isn't owned by EximiaIT.

But your packages are great as they are, I wouldn't think there is anything missing 🙂

Some of the greatest publishers are in a similar situation. Like Bitnami, for example. They publish a ton of great charts that are widely used for a lot of software. But they don't really own the underlying software, so the official status doesn't apply either. However, they usually have lots of stars on each package and users can see they are the publisher, which helps getting users' trust.

The official status is helpful sometimes when there are multiple options to pick from for the same "thing", and we just want to let users know that the publisher owns the software behind the artifact. This is just one extra piece of information to help them make their decision. They may also look at how popular it is (i.e. stars have more weight in search results), who's behind it, how often new release are published, if it's actively maintained, etc. But in your case I haven't seen a similar artifact yet. And if/when it eventually exists, it may not be official either, so none would have any advantage regarding this over the other option 😉

**Comment by mbecca** [comment]
I understand perfectly, thank you for your time. Kind regards.

**Comment by tegioz** [comment]
No problem, thanks for understanding!
