### ISSUE TITLE
[BROKEN] alertmanager-gchat

### ISSUE THREAD

**Issue by m-kuhn** [artifacthub/hub#3228]
The repository https://artifacthub.io/packages/helm/alertmanager-gchat/alertmanager-gchat  links to https://ramiroduarteavalos.github.io/library/charts which results in a 404.

**Comment by tegioz** [comment]
Hi @m-kuhn 👋

That's the Helm repository url and it looks like the [index.yaml](https://ramiroduarteavalos.github.io/library/charts/index.yaml) file is served correctly (it's not required to provide an `index.html` file). However, it looks like the url of one of the packages hosted in this repository isn't working fine (<https://ramiroduarteavalos.github.io/library/charts/alertmanager-gchat-1.0.0.tgz>, the other one is ok).

The chart provides the email of a maintainer (accesible from AH on the right column in the package details view). It'd be great if you could ping them so that they could fix it 🙂

**Comment by m-kuhn** [comment]
Thank you for the analysis, @tegioz 
I have created an issue on the github repository instead of an email, I think that will allow for a more streamlined discussion.
