### ISSUE TITLE
Select latest stable version in chart overview by default

### ISSUE THREAD

**Issue by krichter722** [artifacthub/hub#3559]
**Describe the bug**
In the chart overview page the chart description for the latest released version is shown. If the latest release is alpha the user is tempted to consider the page shown by default to be the best instructions to configure that chart. However, the alpha release is not the first choice in most cases and the downloaded version is most likely the latest stable and thus does not match the description.

I made this experience and figured it out after some time, but the is lost anyway.

**To Reproduce**
Check https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard for example. It's nice to see upcoming changes, but I can select that from the version list.

**Expected behavior**
It'd be more intutive if https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard/6.0.8 was shown at https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard/.

**Screenshots**
./.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Firefox
 - Version: 120.0.1

**Smartphone (please complete the following information):**
./.

**Additional context**
I can re-open this as a feature request. It's not really a bug, but also not really a feature request.

**Comment by tegioz** [comment]
Hi @krichter722 👋

We've been discussing this a bit in the past. Please take a look at the comments below for some more information:

https://github.com/artifacthub/hub/issues/973#issuecomment-745220868
https://github.com/artifacthub/hub/issues/1359#issuecomment-851218699

We provide some mechanisms for publishers so that they can decide which behavior works best for them, like the `ignore` [1] and `pre-release` [2] features. But at the moment, for the same reasons discussed previously, we don't have plans to modify the default behavior.

Hope this helps 🙂

[1] *to request AH to not index packages matching certain patterns*
[2] *to highlight certain packages in the UI to let users know the version displayed is not stable yet*
