### ISSUE TITLE
TypeError: "undefined has no properties"

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#362]
If I go to Bitnami project repos and look at their charts I get a white screen. For example, https://artifacthub.io/package/chart/bitnami/jenkins

The API is returning a response but when React goes to render it the things break.

![Screen Shot 2020-05-04 at 2 25 32 PM](https://user-images.githubusercontent.com/62991/80999764-31d84000-8e13-11ea-93a7-d4f0b4043897.png)

cc @carrodher

**Comment by carrodher** [comment]
There are some charts that are render properly: https://artifacthub.io/package/chart/bitnami/sugarcrm, https://artifacthub.io/package/chart/bitnami/mean, https://artifacthub.io/package/chart/bitnami/mariadb-cluster, https://artifacthub.io/package/chart/bitnami/tensorflow-inception, https://artifacthub.io/package/chart/bitnami/bitnami-common and https://artifacthub.io/package/chart/bitnami/common. In the end, 6 of 75.

Something curious: Those charts that are properly shown are not following the automated Bitnami release process, the two common ones because both are like a helper chart, and the rest (mean, sugarcrm, etc) was removed a long time ago (but we didn't follow a good deprecation process). They didn't appear in the [GH repo](https://github.com/bitnami/charts/tree/master/bitnami) nor are receiving updates.

In the same way, I am receiving this kind of errors in the control panel, not sure if it is related or not:
```
error registering package kubewatch version 0.8.6: ERROR: duplicate key value violates unique constraint "snapshot_digest_key" (SQLSTATE 23505)
error registering package suitecrm version 5.4.0: ERROR: duplicate key value violates unique constraint "snapshot_digest_key" (SQLSTATE 23505)
```

I have a lot of similar entries but with different chart name and version

**Comment by carrodher** [comment]
Wow, that was fast! I just added some info I have, just in case it can help with something although the issue seems to be solved in the code (although not deployed yet I guess)

**Comment by tegioz** [comment]
Deployed!

**Comment by tegioz** [comment]
> In the same way, I am receiving this kind of errors in the control panel, not sure if it is related or not:
> 
> ```
> error registering package kubewatch version 0.8.6: ERROR: duplicate key value violates unique constraint "snapshot_digest_key" (SQLSTATE 23505)
> error registering package suitecrm version 5.4.0: ERROR: duplicate key value violates unique constraint "snapshot_digest_key" (SQLSTATE 23505)
> ```
> 
> I have a lot of similar entries but with different chart name and version

Hi @carrodher 

Thanks for sharing this error.

The digest of a chart version is supposed to be unique, to avoid having duplicate entries. This error means (some errors are not very descriptive yet, sorry about that) that there is another chart version registered using that digest (it could be from the Bitnami repo or from another one). Is it possible that the same chart is also in the Stable or Incubator Helm repos? Or that multiple versions are using the same digest in the Bitnami repo? I can check for any specific case if you'd like.

**Comment by carrodher** [comment]
Hi, thanks for the response.

Yes, that seems to be the issue. We were publishing some of the Bitnami charts in the stable repo and also in the Bitnami repository, the same versions at the same time. Since the stable repo EOL announcement, we stopped sending new versions to the stable repository and we deprecated the charts in stable in favor of the Bitnami repository. So yes, there are a lot of versions duplicated in around 30 charts.
Using kubewatch as example:
```
▶ helm search repo kubewatch
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/kubewatch	1.0.12       	0.0.4      	Kubewatch notifies your slack rooms when change...
stable/kubewatch 	1.0.9        	0.0.4      	DEPRECATED Kubewatch notifies your slack rooms ...
```
That means versions <1.09 are going to be duplicated:
```
▶ helm fetch stable/kubewatch --version 0.8.6
▶ sha256sum kubewatch-0.8.6.tgz
82590c8248f7dbeda01a55b8c4789223846dda1feb576cd9d9cd9676c7014fc7  kubewatch-0.8.6.tgz
▶ rm -rf  kubewatch-0.8.6.tgz
▶ helm fetch bitnami/kubewatch --version 0.8.6
▶ sha256sum kubewatch-0.8.6.tgz
82590c8248f7dbeda01a55b8c4789223846dda1feb576cd9d9cd9676c7014fc7  kubewatch-0.8.6.tgz
```

I don't have any preference if it is only possible to have charts with the same digest in one place feel free to use the approach that better fit your requirements.

**Comment by carrodher** [comment]
BTW, I can confirm the issue is solved, i.e https://artifacthub.io/package/chart/bitnami/wordpress

**Comment by tegioz** [comment]
Hi @carrodher 

Do you think it would be possible to delete the duplicated ones from one of the sources? 

If the Bitnami repo is their new official home, maybe they could be removed from the Helm repo. Soon after they are removed from the repo `index.yaml` file, ArtifactHub will catch up and delete them as well, leaving room for the ones currently failing to be registered successfully.

If this is not an option please let us know and we'll think of something else.

Thanks again!

**Comment by carrodher** [comment]
I am not sure about this solution as users expect to have the previous version in both repositories. If someone was using an old version in the stable repo or in the bitnami one, this user expects `helm install --version X.X.X` working.

In this case, note that there are duplicated versions, yes, but duplicities between an active chart and a deprecated one, maybe it is a good idea when detected duplicity, check if one of the sources is already duplicated, and in that case use the active one.

Probably @mattfarina has more ideas about this topic.

**Comment by tegioz** [comment]
I understand, makes sense @carrodher.

I thought that `stable` and `incubator` repos would be [de-listed from the Helm Hub](https://github.com/helm/charts#status-of-the-project) eventually, so if I understood correctly users won't be able to continue using those repos soon anyway.

Enforcing digest uniqueness only for entries with the `deprecated` flag disabled sounds good. That way we would allow multiple duplicates provided they were deprecated.

We can relax this restriction, it won't be a problem at all. It was just an extra precaution to avoid someone to add an existing repo and all its packages under a different organization or user easily.

**Comment by tegioz** [comment]
Hi @carrodher. The unique digest restriction has been relaxed. Please let me know if you don't see the old versions in the Hub or the same error appears in the logs. Thanks!

**Comment by carrodher** [comment]
Thanks @tegioz, the logs are perfect now!
