### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [artifacthub/hub#3620]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by tegioz** [comment]
Hi @thisisobate 👋

The trademark disclaimer is actually being displayed on <https://artifacthub.io>.

<img width="1503" alt="trademark" src="https://github.com/artifacthub/hub/assets/1213902/ce285881-8459-40fa-aa32-15bbfdd3cc74">

Due to the nature of the Artifact Hub site, CLOMonitor (which we also maintain! 😅) isn't able to detect it yet (more details about this [here](https://github.com/cncf/clomonitor/issues/1194#issuecomment-1662496599)). In the meantime we've declared an exemption to make CLOMonitor happy 😇

<img width="894" alt="exemption" src="https://github.com/artifacthub/hub/assets/1213902/5c952092-975d-48e6-82ba-36115836dd62">

Thanks for the heads up!
