### ISSUE TITLE
Verified badge in the controlplane is not aligned with badge on the public listing

### ISSUE THREAD

**Issue by StarpTech** [artifacthub/hub#3756]
Chart: https://artifacthub.io/packages/helm/cosmo-platform/cosmo

Controlplane:
<img width="177" alt="image" src="https://github.com/artifacthub/hub/assets/1764424/56b7237e-a019-4887-aecd-acd370249a41">

Listing:
<img width="945" alt="image" src="https://github.com/artifacthub/hub/assets/1764424/cfcb0938-c158-4b83-8bf3-c5bf27160029">

**Comment by tegioz** [comment]
Hi @StarpTech 👋

The badge in the control panel, which indicates that a full repository is marked as official, is only visible to the publisher. In the rest of the sections of AH, the badge is displayed at the package level. We can grant the official status at both the repository and package level. But most of the time, we do it at the package level.

The reason is that sometimes, when the official status is requested, the packages on it fulfill the requirements. But later, at some point, it's easy to forget that anything on it will be marked as official. And sometimes, another package is added to an official repo that wasn't supposed to be official. To avoid this kind of issue, even though is a bit more manual work, we do it per package often.

We have plans to remove that icon from the control panel to avoid this kind of misunderstandings 😇

Hope this helps 🙂
