### ISSUE TITLE
ArtifactHub doesn't detect OCI-based charts using semver tag with + char replaced by _

### ISSUE THREAD

**Issue by JuniorJPDJ** [artifacthub/hub#3762]
**Describe the bug**
Helm utility automatically replaces `+` with `_` when pushing charts to OCI-based repository. ArtifactHub entirely skips versions with this character as it thinks it's non-semver compliant. OCI doesn't natively support `+` character in tags.

I'm uploading PR charts with `0.0.0+PR-#` versions and those are not visible in the AF.

**To Reproduce**
1. Add OCI-based Charts repository to AF.
1. Upload chart with `+` character in the version using official helm utility (it gets uploaded with `+` sign replaced by `_`).
2. See the ArtifactHub not grabing it at all.

**Additional context**

**Comment by tegioz** [comment]
Hi @JuniorJPDJ 👋

> ArtifactHub entirely skips versions with this character as it thinks it's non-semver compliant

ArtifactHub **requires** packages versions to be valid semver. The problem is that `0.0.0_PR-1` is not actually a valid semver version. You can test it yourself [here](https://go.dev/play/p/u65zT3VWWza), which is basically [the same as we do when processing the tags of an OCI reference](https://github.com/artifacthub/hub/blob/31cb29e1188d24ada720756b02c8e9ad6a2067f4/internal/oci/oci.go#L184-L186). But even if it was, we could still have an issue, as we could have processed the version but display incorrect installation instructions (i.e. displaying an `_` in the installation command expecting the Helm CLI tool to replace it, or viceversa).

I understand the need [for this workaround](https://github.com/helm/helm/blob/14d0c13e9eefff5b4a1b511cf50643529692ec94/pkg/registry/client.go#L45C8-L50) on the Helm side, due to the OCI references naming rules. We could consider reverting that change when listing tags for OCI based Helm repositories, but we also need to be mindful about other artifact kinds. Let us think about this a bit to see the implications it may have on other parts of Artifact Hub 🙂
