### ISSUE TITLE
Registry with mixed content type should not log errors for mismatch

### ISSUE THREAD

**Issue by chrismuellner** [artifacthub/hub#3801]
**Is your feature request related to a problem? Please describe.**
When storing different types of OCI artifacts in the same repository the Artifacthub logs show an error for each tag that does not match the kind configured for the Artifacthub repository, e.g. repository of kind "Helm charts" errors for each tag containing an "image" or "Image manifest".

Repository [public.ecr.aws/dynatrace/dynatrace-operator](https://gallery.ecr.aws/dynatrace/dynatrace-operator) contains tags with image (manifests), e.g. `v1.1.0` or `v1.1.0-amd64`, and tags with helm charts, e.g. `1.1.0` (no `v` prefix):
1. Repository is added to Artifacthub using kind "Helm chart" and Url in [OCI format](https://artifacthub.io/docs/topics/repositories/helm-charts/#oci-support): `oci://public.ecr.aws/dynatrace/dynatrace-operator`
2. Tags containing helm packages are successfully processed and show up in the [repository listing](https://artifacthub.io/packages/helm/dynatrace/dynatrace-operator), e.g. `1.1.0`
3. All other tags lead to error logs in the repository
```
...
error preparing package: error loading chart (oci://public.ecr.aws/dynatrace/dynatrace-operator:v1.1.0): layer not found (package: dynatrace-operator version: v1.1.0)
error preparing package: error loading chart (oci://public.ecr.aws/dynatrace/dynatrace-operator:v1.1.0-amd64): layer not found (package: dynatrace-operator version: v1.1.0-amd64)
error preparing package: error loading chart (oci://public.ecr.aws/dynatrace/dynatrace-operator:v1.1.0-arm64): layer not found (package: dynatrace-operator version: v1.1.0-arm64)
error preparing package: error loading chart (oci://public.ecr.aws/dynatrace/dynatrace-operator:v1.1.0-ppc64le): layer not found (package: dynatrace-operator version: v1.1.0-ppc64le)
...
```

**Describe the solution you'd like**
Since this is a repository with both images and helm packages not all tags are expected to be helm packages and missing helm packages for a tag should not lead to error logs.

**Describe alternatives you've considered**
Different repositories for helm chart and image are an option, but it would be nice to keep it all in a single repository. There are currently no other issues using a single repository.

Another option would be to have a toggle to ignore the tags with different metadata in the repository configuration.

**Additional context**
Swallowing the errors may be not be an ideal solution, but by selecting "Helm chart" as kind it's already configured that those are not important for the repository. If a tag with the right, matching metadata for a helm chart has an issue the error logs would still show.

I did not want to just create a PR as I'm unsure what the preferred behaviour is:
- List of tags could be filtered to only chart content (`application/vnd.cncf.helm.chart.content.v1.tar+gzip`) and legacy chart content (`application/tar+gzip`)
  - seems this metadata is currently only loaded on actual layer pull, so would _probably_ require additional requests
- Error could be ignored when pulling a layer that does not exist because of mismatch in layer media type

**Comment by tegioz** [comment]
Hi @chrismuellner 👋

Some context first about how Artifact Hub indexes Helm charts stored in OCI registries 🙂

AH polls repositories periodically, currently every 30 mins. In the case of Helm charts OCI based repositories, we first list the tags available in the OCI registry for the provided repository, collecting the semver-ish ones. Once we have this list, we compare it against the list of registered versions. If the registered versions matches the versions available in the OCI registry repository, we're done and no further requests to the OCI registry are needed. This is what happens on most of the periodic checks. When a new version is detected in the OCI registry, we pull the corresponding image to index and register it.

Other kinds of artifacts present in the same repository in the OCI registry aren't registered in AH. This means that the list of versions registered will never match the list of versions available, forcing us to pull the corresponding image every time to try to process it. We could indeed filter out content after that pull and not raise errors, but as you mentioned, this would require extra requests to the registries to fetch the manifest. This same issue may affect other tools as well, whether they raise an error about it or not, as they'd need to fetch the manifest to inspect its content and decide.

There are thousands of charts repositories in AH, often with multiple charts each, and each of those charts may have a lot of versions. We need to be careful because this adds up over time, making the tracking process slower and more expensive. In addition to that, and more importantly, we may end up being rate limited by registries (some already have rate limits in place). So IMHO we should try to keep the number of requests to the minimum possible.

I think the alternative solution you proposed is the best: different repositories for Helm charts and other artifacts. Actually, if we end up having rate limit problems with some registries, we may need to enforce this somehow by only processing repositories that only contain the artifact kind we're expecting.

Hope this makes sense, and thanks for bringing this up! 🙂

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
