### ISSUE TITLE
[OFFICIAL] kwok

### ISSUE THREAD

**Issue by wzshiming** [artifacthub/hub#3916]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: kwok
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://kwok.sigs.k8s.io/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Subproject of Kubernetes
- **Source code URL** *(if available)*: https://github.com/kubernetes-sigs/kwok
- **Other relevant URLs:** [I am the founder of kwok](https://github.com/kubernetes-sigs/kwok/graphs/contributors)

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @wzshiming 👋

Could you address the following points? 🙂

- The [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) badge isn't being displayed yet in the `kwok` package

- The *display name* of the organization you are using to publish the package is `Kubernetes SIGs`, whereas the organization *name* is `kwok`. There is already an organization named [Kubernetes SIGs](https://artifacthub.io/packages/search?org=kubernetes-sigs) registered in Artifact Hub, so this can be confusing for users. If your intention was to publish it under the Kubernetes SIGs organization, it'd be great if you could get invited to it so that you can publish this new repo. Otherwise, if you prefer to publish it under the `KWOK` organization, it'd be better if you changed the display name to KWOK as well.

Thanks!

**Comment by wzshiming** [comment]
@tegioz Thank you, I have done it.

**Comment by tegioz** [comment]
Done!
