### ISSUE TITLE
Configuring basic auth causes reauthentication all the time in Chrome

### ISSUE THREAD

**Issue by sneaker-xc3** [artifacthub/hub#4017]
**Describe the bug**
When using Chrome and when artifacthub is setup with basic authentication even after the first login through the basic auth, Chrome will ask again and again for the credentials. One is not logged in to artifacthub itself.

**To Reproduce**
* Steps to reproduce the behavior:
* Configure basic auth for artifacthub
* Navigate to the artifacthub page with chrome browser
* Enter password
* Hit refresh,  or go to docs, basic auth request will reappear again.

**Expected behavior**
After entering the basic auth credentials once it should not ask again.

**Additional context**
The error is probably caused by a call to the api/v1/users/profile which returns a 401. Firefox e.g. does not react to it but chrome causes the user to enter the password over and over again.
The current work around is to also log into the webapp itself. then the api request returns 200. and everything seems fine.
The behavior can also be explored on https://artifacthub.io if you open the developer console. you see 401s happening. Your server log must be full of it.

**Comment by tegioz** [comment]
Hi @sneaker-xc3 👋

The call to `api/v1/users/profile` returning a `401` is expected when the user is not logged in, this is something intentional. 

Please note that the basic auth feature is not actually meant to log into Artifact Hub. I understand this may seem a bit confusing, but this feature was added at the very beginning of Artifact Hub to collect feedback from some users while it wasn't ready yet. We added this minimal basic auth as a gate to restrict access to the application itself, where you can log in if you wish.

**Comment by sneaker-xc3** [comment]
Hi @tegioz 

Thanks for the explanation. It does make sense now why it never caused problems for you. 

However from a web development perspective I am not sure if this is the best solution as it also pollutes log files with unneeded errors. I did a short debugging session in the browser and found out that somewhere there is the information it is a guest user or even undefined. The call to the profile api could just simply only be made if that the user != guest or user != undefined. Or can you elaborate on why it is intentional to call the profile in any case. 
I think returning 401 from the backend is not the problem. The issue is asking for a profile in any case you already know that there would be no profile.
I would even provide the pull request for it.

**Comment by tegioz** [comment]
No worries, happy to help!

That's intentional as well, so we'd rather leave it as it is 😇

IIRC that was used for a number of reasons, but it's been a long time 😅 Of the top of my head, I think one of the reasons was to verify that a session was still valid, to prompt the user to log in back. But there were some more (something related to the theme, some redirections in the control panel, etc). But @cynthia-sg or I would need to look into it a bit further to provide exact details.

Thanks anyway for the offer, but I think we're good.

Will close this issue for now, feel free to reopen if needed 🙂
