### ISSUE TITLE
[OFFICIAL] SolarWinds

### ISSUE THREAD

**Issue by jaroslav-fedor-swi** [artifacthub/hub#4029]
- **Repository name** *(in `artifacthub.io`)*: solarwinds
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://www.solarwinds.com/solarwinds-observability
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/solarwinds/swi-k8s-opentelemetry-collector
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi @jaroslav-fedor-swi ,

all packages must have a `README.md` file to be granted the official status. Could you please add it?

Thanks

**Comment by jaroslav-fedor-swi** [comment]
Hi @cynthia-sg,

Readme is present at the same level as index.yaml - https://github.com/solarwinds/swi-k8s-opentelemetry-collector/blob/gh-pages/README.md

Not sure why it is not properly loaded on artifacthub side.

**Comment by tegioz** [comment]
Hi @jaroslav-fedor-swi 👋

Artifact Hub expects the `README.md` file to be part of the chart package, as described in the [Helm docs](https://helm.sh/docs/topics/charts/#the-chart-file-structure).

At the moment it isn't in it (you can check the link below as an example), that's why Artifact Hub cannot process it correctly.

<https://github.com/solarwinds/swi-k8s-opentelemetry-collector/releases/download/swo-k8s-collector-4.1.0-alpha.2/swo-k8s-collector-4.1.0-alpha.2.tgz>

**Comment by jaroslav-fedor-swi** [comment]
Hi @tegioz, 

I was able to release new pre-release version containing readme document. 

Is there anything else blocking the request?

**Comment by tegioz** [comment]
Awesome, official status granted 🙂
