### ISSUE TITLE
Docker rate limit issues of artifact.io tracker

### ISSUE THREAD

**Issue by pat-s** [artifacthub/hub#4148]
I am getting more than a dozen emails per day lately (multiple ones every few hours) as the tracker is running into rate limits:

```
error getting repository metadata: failed to copy: httpReadSeeker: failed open: unexpected status code https://index.docker.io/v2/devxygmbh/r-alpine/manifests/sha256:cb528119f6ea9b1365b8b5b6434d74ccce56edebe35f2ade7d205a3a4142a183: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
error preparing package (tag: 4): error getting metadata: GET https://index.docker.io/v2/devxygmbh/r-alpine/manifests/4: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
error preparing package (tag: latest): error getting metadata: GET https://index.docker.io/v2/devxygmbh/r-alpine/manifests/latest: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Besides the issue, I couldn't find a way to turn of email notifications for tracking logs.

As the error is quite generic, I would assume more people getting these if the tracker runs into a rate limit. 

Given the amount of mails/day, this is somewhat urgent.

**Comment by tegioz** [comment]
Hi @pat-s 👋

This issue is due to a problem with our Docker-Sponsored Open Source subscription. We are working on it to get it restored as soon as possible 🙂

In the meantime, you can opt-out of the tracker notifications from the control panel.

Thanks for reporting it!

**Comment by pat-s** [comment]
@tegioz Thanks. I eventually found were to opt out - I had to switch context from the org to the user as the opt-out is only available in the latter.

**Comment by jon-nfc** [comment]
same issue. 

I also don't see the point on receiving the email if i can't action it.

**Comment by tegioz** [comment]
Hi @jon-nfc

Processing repositories can fail for a number of reasons, and sometimes it can be tricky to know in advance which ones will be actionable. But even when errors are not actionable, it can be helpful for some publishers to be aware of them (i.e. they may be asked by their users why their content isn't up to date on `artifacthub.io`). So we prefer to let publishers know that something is going on with their repositories by default and let them opt-out of those notifications when they wish.

**Comment by pat-s** [comment]
@tegioz I am still receiving mails every few minutes even though I have opted-out of them in the admin panel. This is going on for several days now and I've received 100-200 mails so far. 

If this doesn't stop and I can't find a way to opt out soon, the only way left to tackle this is likely to delete the account 👀️ 
Appreciated if this could be tackled soonish. 

Wondering why so few people complain about this? Maybe everybody else redirects these mails to spam?

**Comment by tegioz** [comment]
@pat-s notifications opt-out should be working fine. Did you do it for all repositories affected? Can you show to me what do you have in settings/subscriptions/repositories?

We pull images from the Docker Hub for two reasons: to scan images on any package kind for security vulnerabilities and to track packages of `container image` kind hosted there. The former would affect a lot of users, so we've paused the scanner temporarily until this issue is resolved. Regarding the latter: the number of packages of `container image` kind is low, and many of them are hosted in a different registry (GitHub, Google, GitLab, etc, which aren't affected as they don't rate limit pulls the same way). So it's expected that only a relatively small number of users are experiencing problems.

**Comment by tegioz** [comment]
Actually, to be precise, 16% of the packages of `Container Image` kind are hosted in the Docker Hub registry (the most popular is the GitHub registry, with 34%).

**Comment by jon-nfc** [comment]
> Hi @jon-nfc
> 
> Processing repositories can fail for a number of reasons, and sometimes it can be tricky to know in advance which ones will be actionable. But even when errors are not actionable, it can be helpful for some publishers to be aware of them (i.e. they may be asked by their users why their content isn't up to date on `artifacthub.io`). So we prefer to let publishers know that something is going on with their repositories by default and let them opt-out of those notifications when they wish.

@tegioz, agreed sometimes it is helpful to know as you state some are actionable. Like when you get the labels wrong. I do find it hard to believe that "It's tricky to know which it advance are actionable". The developer who added the feature would/will have the ability to denote this. 


@pat-s, I disabled the notifications by logging in and:

- navigate to control panel
- change context to your user account if you use an org
- click settings tab
- under repositories click "opt-out"
- search for your repo by name
- I then clicked on tracking errors (don't know if right, however haven't got any notifications)

hope this helps.

**Comment by tegioz** [comment]
@jon-nfc when interacting with a lot of different third party services (multiple different OCI registries in this case), this may not be always clear. The developer may not know in advance all the possible errors each of the services may raise and under what circumstances, those errors may not be clear sometimes (specially when things fail in unexpected ways or in cascade), and they can change (their content or meaning) over time.

That's why I mentioned that *sometimes* it can be tricky to know in advance if they'll be actionable. So we find it safer to always forward them, even though we know sometimes it can be a false alarm. But even false alarms can be helpful to bring awareness of them problem to the relevant parties. In this case, we knew of it, but if we hadn't noticed for whatever reason, @pat-s ping would have been key to get it fixed faster.

**Comment by tegioz** [comment]
Our Docker-Sponsored Open Source subscription has been restored, the issue should be now resolved 🎉

Please let us know if you keep receiving this error going forward.

Thanks for your help! 🙂
