### ISSUE TITLE
Artifact Hub exposes templates of private repositories

### ISSUE THREAD

**Issue by gaelgatelement** [artifacthub/hub#4156]
**Describe the bug**
Hub is exposing templates in the UI for helm charts protected behind private repositories.

**To Reproduce**
1. Add a private repository
2. Wait for helm charts to be imported
3. Go to the chart pages - Templates are available and displayed

**Expected behavior**
Templates should not be displayed as they break the private aspect of the repositories.

**Comment by tegioz** [comment]
Hi @gaelgatelement 👋

> *Reference for future readers*: private repositories are not allowed in the `artifacthub.io` deployment, but it's a feature supported by the Artifact Hub software that can be enabled on other deployments.

This is intentional, it's working as expected. When a repository is added to Artifact Hub, it's meant to be fully explorable from the Artifact Hub UI. This means that all information we collect during its processing can be displayed in the UI. We added this feature to allow repositories that required credentials to be added to Artifact Hub, but not to enable keeping some parts of the packages content private.

Hope this helps 🙂

**Comment by gaelgatelement** [comment]
Thanks for your quick and clear answer !
