### ISSUE TITLE
"official" artifacts

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#542]
Note, I'm neither sure of the right way to approach this or the name on the label.

We need a way to mark artifacts as those coming from the organizations that supply the component. For example, if Oracle put out an operator for MySQL or the Cert Manager chart put out behind the people behind Cert Manager.

The idea is to provide a known association between those who "own" the product or project being deployed by the packaging artifact.

This can be displayed and used for sorting in search results.

We will not be able to alter the chart specification for this. That would not work as it could be gamed or faked. We will likely need a process to apply for this and have it applied by an admin.

**Comment by tegioz** [comment]
Artifact Hub now displays an Official label in repositories marked as such and the packages available on them. A new filter has been added as well to the packages search page that allows listing packages in official repositories.

<img width="1230" alt="official" src="https://user-images.githubusercontent.com/1213902/92475634-fe9d2780-f1dd-11ea-81ea-9c09c9a0f30c.png">

**Comment by tegioz** [comment]
We could start defining how the process to apply for that status would be :)

**Comment by mjpitz** [comment]
It would be nice if people didn't have to apply for this so to speak, but I understand the desire to want to. It'd be nice if an org could be verified for the charts they produce and own (the Argo community for example). However, not every chart an organization produces is an official one.

The current "Verified Publisher" process verifies that the author owns the target repository. It doesn't verify that the code or processes that are contained within that repository are the authors. For example, I can produce a Helm Chart for MySQL with a Verified Publisher status. For something to be "official", I'd say I need to own both the configuration AND the source code. However, these can live in different locations (e.g. prometheus and prometheus-community).

It seems like starting with the verified publisher and adding in a way to verify the source would be a good start towards some automated process.

**Comment by datamattsson** [comment]
Is there a formal process to apply for an "Official" badge yet? HPE Storage is in need of one.

**Comment by mjpitz** [comment]
@datamattsson I just opened an issue and it was done pretty quick

**Comment by consideRatio** [comment]
I'm a maintainer in the JupyterHub GitHub organization looking to prepare for requesting an official status of a Helm chart repo where we currently host three charts, of which only two would be official.

Questions that arise:
- Will the official stamp be applied on a repo level only, or should/could it be applied on a package level?
- Will the criteria be 100% that of packages/charts are official to have the repo become official stamped? Should this change depending on if the artifacthub-repo.yml ignores certain packages/charts?

Practically, I look to decide if the github org im part of should put in work to split apart our Helm chart repo into a helm chart repo with only official charts and one with only non-official charts.

**Comment by tegioz** [comment]
Hi @consideRatio 

- Yes, at the moment the official stamp is applied at the repo level. There is an issue open to consider doing it at the package level (#972).
- The second one is a bit more tricky. All packages indexed from the repo should be official, yes, as otherwise it could be misleading for users. But if the one that isn't will be set to be ignored in the `artifacthub-repo.yaml` file, I don't really see a problem, as it won't be available in Artifact Hub. However, the fact that AH ignores it doesn't make Helm to ignore it. If a user only adds repositories he trusts to be official to Helm and searches for something later on, your ignored packages will still show up.

**Comment by tegioz** [comment]
We have now an issue template to apply for the official status. If you notice there's something missing or wrong, please let us know. Thanks! 🙂 

<img width="1297" alt="Screen Shot 2021-02-05 at 13 09 26" src="https://user-images.githubusercontent.com/1213902/107032111-90bc5280-67b3-11eb-9291-5d7ad4e45bc0.png">

**Comment by consideRatio** [comment]
@tegioz thanks for your work on this!

> The repository _only_ contains official packages.

I see two interpretations of this for Helm chart artifacts and their repos

1. The artifactshub repo only contains official packages, meaning, the Helm repo can contain non-official charts but these would have to be ignored in the artifactshub config file so the artifactshub repo only contain official charts.
2. Both the helm repo and the artifactshub repo only contain official packages, even if only the official ones are exposed in artifactshub because the non-official ones are ignored.

I guess the question boils down to if the official stamp requires everything featured in artifactshub to be official, or the entire underlying provider of artifacts to only contain official artificats.

**Comment by tegioz** [comment]
Thanks @consideRatio!

If the non-official packages will be set to be ignored in the `artifacthub-repo.yaml` file, IMHO I don't really see a problem, as they won't be available in Artifact Hub. However, the fact that AH ignores them doesn't make Helm to ignore them. If a user only adds repositories he trusts to be official and searches for something later on from the CLI, the ignored packages will still show up.

Let's see what others think about this, I'm happy to make all the necessary changes until we get this right 👍

**Comment by consideRatio** [comment]
@tegioz thanks!

Is it correct that artifactshub only feature the Helm charts rather than the Helm repo itself? If so, I suggest that official status is accepted for a Helm repo that only surfaces official charts to artificatshub even though it contains more. I reason that if artifactshub only features the charts rather than the chart repositories themselves, the stamp is reasonably considered to be stamping the chart rather than the chart repo, and due to this won't be misleading any users.

**Comment by tegioz** [comment]
Good point. I was going to mention it in my previous comment to kind of "justify" that we wouldn't be misleading users going on this way. But then I remembered that it's actually exposed at the moment, but only visible to the repository owner, as shown in the screenshot below. And we may end up displaying that flag somewhere else because in the end it belongs to the repository, so we'd need to be careful. 

<img width="969" alt="Screen Shot 2021-02-05 at 14 10 56" src="https://user-images.githubusercontent.com/1213902/107037912-117f4c80-67bc-11eb-8567-72cf70e51cd1.png">

In addition to that, and more importantly, we offer a [public API](https://artifacthub.github.io/hub/api/#/Repositories/get_repositories_org__orgName_) that's exposing some of the information available in `artifacthub.io`. The repository information can be fetched from several endpoints, and among other pieces of data, it contains the official flag. Someone could build a plugin to verify that users only install charts from official repositories (actually this gave me some ideas 😄💡) based on this information.

Please note that I'm not against this, it's actually the opposite. As I mentioned above, I don't really see a problem as long as the non-official packages are not visible in AH. I just wanted to raise the concern to see what others think 😇 .

**Comment by tegioz** [comment]
In addition to requesting the `official` status for a repository, it is now possible to request it for individual packages (#1138).
