### ISSUE TITLE
Search facets don't allow filtering on results from subsequent pages

### ISSUE THREAD

**Issue by scottrigby** [artifacthub/hub#605]
Example (Artifact Hub chart):

- https://artifacthub.io/packages/search?page=1&ts_query_web=artifacthub&kind=0 displays the facet `Publisher > Organization > Artifact Hub (1)`
- But https://artifacthub.io/packages/search?page=1&kind=0 doesn't display the `Artifact Hub` facet, even though it will be in one of the subsequent pages.
- When paging to page 2 https://artifacthub.io/packages/search?page=2&kind=0 Artifact Hub chart appears but the facet is also not there

May be related to #530

**Comment by tegioz** [comment]
Hi @scottrigby 

Thanks for reporting this. You are right, it's related to #530 and @cynthia-sg is working now on it :) 

Facets entries come from your text search, so that you can narrow them down. A few weeks ago we changed how this worked, limiting the facets options to the 10 top entries. The reason was that sometimes the list was huge, and the UI as it was wasn't prepared to scale to such large number of options.

We've been discussing it this morning and we've come up with some improvements. The new version, in addition to suggest some of them, will allow searching for entries on each of the options blocks (typeahead behavior).

I'll close this one in favor of #530 if you don't mind. Thanks again!
