### ISSUE TITLE
Package READMEs don’t render relative links

### ISSUE THREAD

**Issue by scottrigby** [artifacthub/hub#629]
This was just brought to my attention, and I added some thoughts here https://github.com/jenkinsci/helm-charts/issues/27#issuecomment-687110637

WDYT? I prefer the second option. Could be part of one of the artifact hub metadata files we're introducing (for owners and verification)?

**Comment by tegioz** [comment]
Hi @scottrigby 

That was intentional as a temporary solution, to avoid displaying them broken. This also applies to images, which we don't show at the moment either when they use relative links. There was a related issue with anchors but IIRC that one was solved in Artifact Hub (it was a problem in Helm Hub as well last time I checked).

I prefer the second option too, as I don't think we should store and serve all files inside the chart linked from the README. But I'm not really sure if this the best way to proceed, as there are some important details we should keep in mind:

- This may not be very intuitive, and many users many not even realize this is a problem or how to solve it. 
- Repository publishers will need to make sure they are serving those files somewhere, which may require an additional effort in some cases (setting it up and maintaining it).
- In addition to that, we shouldn't forget that **each package version has its own README file** (we store them all), and the content of the files referenced from the README file *is expected to change* (the same way the README file evolves over time). So providing a single source url with a plain structure may not be enough if *multiple versions of the same linked files* can be referenced, as we might be displaying information not applicable to that version. This would complicate the issue described in the previous point.

These are only some things I had in mind, there may be more to consider 😅 I'll think about it a bit more, thanks!

**Comment by scottrigby** [comment]
Good note about previous versions 🤔 

Thinking about it, I don't know that much would be lost not adding a way to specify source URLs for all previous versions of a chart. Some charts have a LOT of previous versions, and given that source code moves around, this might be unrealistic to keep up to date. 

But we would need to allow specifying a chart source URL per chart, not only one per repo (in some cases, the repo is separately hosted than the chart(s).

If we allowed specifying just the current source for a chart, this would help with two things:
- Users would be able to inspect source code if available (and contribute, if allowable)
- The current issue: allowing us to expand relative to full links

That way the worst case is old versions READMEs would maintain current behavior of removing the broken links.

**Comment by tegioz** [comment]
Hi @scottrigby 

I'm not sure if it's nice to have a workaround that makes relative links in READMEs work only for the latest version of a given package, when the source is available (and exposed in certain way) and some metadata info has been set up.

IMHO packages READMEs are just another piece of metadata and they *should not assume anything about how they will be used, or from where or how they'll be served*. Using absolute URIs will always be safe, for all package versions, they are intuitive for publishers and don't require any extra trick to make them work. I think any other solution we come up with will be probably fragile and a bit hacky.

Let's say we have that source URL for a given chart, which could be https://github.com/jenkinsci/helm-charts. That wouldn't be enough to build a relative link from https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md to https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md (both are at the same level, but the path to them would be unknown to us). Asking the publisher to write relative links using `blob/main/...` is not nice, branch dependent and may not work well with Github markdown as [they do that conversion automatically](https://github.blog/2013-01-31-relative-links-in-markup-files/). Gitlab uses a different path for blobs. Using https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins as the source URL would have worked in this case, as Github redirects from `tree` to `blob` when needed. But I don't think this is very robust or intuitive (the concrete link used for the source of your chart will impact how relative links in the README file are rendered) and I think encouraging it may not be a good idea.

In [OLM operators](https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md), [Falco rules](https://github.com/falcosecurity/cloud-native-security-hub#adding-a-new-falco-rule) and [OPA policies](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml) (which uses the Artifact Hub package metadata file), READMEs are not even a file, but just a field of the metadata file, which I think helps users not making those assumptions. Probably because of that, only 1 OLM operator out of the 153 we have registered is using a relative link, a license one, which [appears broken at operatorhub.io](https://operatorhub.io/operator/pystol). None of the others use them, which I think is great.

On the other hand, having a chart source URL to display in Artifact Hub would be great. At the moment we display all the links in the sources section of the `Chart.yaml` file, but the result sometimes is not nice as users use that section to include extra links (please see https://github.com/artifacthub/hub/issues/634#issuecomment-688058072). Having a named links section would be nice too.

**Comment by mattfarina** [comment]
A few thoughts...

- Absolute URLs in README's should be fine. We should document that in Helm and elsewhere.
- Source to Helm charts can be stored in the `Chart.yaml` file. There is a field for that. Do not need it in the README.
- I wonder if data URLs can be used in markdown files to share images?
- Storing the content of other markdown files that you'd get needs to be handled with care. For security. It could lead a few different types of attacks. This is something I would want to put off and, if we do it, handle with lots of care.

**Comment by tegioz** [comment]
I will close this one for now, please feel free to reopen if needed.

**Comment by scottrigby** [comment]
For future ref, I've been recommending all chart READMEs contain absolute URLs. For those who have asked, anchor links are fine.
