### ISSUE TITLE
Allow all Chart.yaml fields to be optionally replaced by artifacthub-pkg metadata

### ISSUE THREAD

**Issue by DirtyCajunRice** [artifacthub/hub#634]
Currently if you only have a Chart.yaml, hub will pull the information out of that and fill what it can.

Proposal:
Allow merging of the metadata from both (not deeply, so that lists are not concatenated), with the pkg.yml trumping. This would allow more flexibility. From what i can see in the code the metadata file is not supported for helm currently.

**Comment by tegioz** [comment]
(Sorry, I clicked on the close button accidentally while reading it, I've just reopened it)

**Comment by tegioz** [comment]
Hi @DirtyCajunRice,

Thanks, this could be interesting. There could be some specific pieces of metadata not available in the Chart.yaml file that may be useful for Artifact Hub. One example that comes to mind would be ability to name links.

**Comment by tegioz** [comment]
Links in the sources section of the `Chart.yaml` file are displayed like this at the moment in Artifact Hub:

<img width="221" alt="Screen Shot 2020-09-07 at 08 01 10" src="https://user-images.githubusercontent.com/1213902/92353388-7dac3600-f0e0-11ea-8452-6c719a50430a.png">

However, links in packages of kind OLM operator look nicer, because its metadata format supports named links:

<img width="221" alt="Screen Shot 2020-09-07 at 08 01 36" src="https://user-images.githubusercontent.com/1213902/92353446-a3d1d600-f0e0-11ea-972d-1d57111b4288.png">

**Comment by DirtyCajunRice** [comment]
Exactly. The major things that i was ecxited to leverage were named links,  modified maintainer names over github usernames, as well as hoping that down the road install blocks in helm readmes could be removed in favor of adding a snippit to the install button

**Comment by tegioz** [comment]
Hi!

I've done some work on this and it's mostly ready (https://github.com/artifacthub/hub/commit/181027ab7c6516cdef327bcc6c23e489b9e5973d). However, I've now some concerns that I'd like to discuss before merging this.

#### The first one is related to what parts should we allow to be used from the Artifact Hub metadata file

Allowing all fields to be overridden can be dangerous and break things. Key fields like the package's `name` or `version` are used for very sensitive matters, so I think we shouldn't allow those to potentially differ from what's in a Helm chart `Chart.yaml` file (or any other package kind metadata).

Allowing just some of them to be overridden is better, but I'm wondering if this may get confusing for users. They may create a complete [Artifact Hub metadata file](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml) to later find out that only parts of it are actually used. And the parts used might vary from a package kind to another.

Somehow this would open the door for two metadata files for the same artifact to not be in sync, which could lead to problems in some cases.

#### Use cases identified so far and impact on the different package kinds we support

So far we've mentioned a few limitations this could solve:

- Operator flag
- Named links
- Modified maintainer names
- Install blocks

The impact varies from kind to kind:

- **OPA**: no impact as it's already using the Artifact Hub metadata file.
- **Falco**: we cannot use this approach at the moment for this package kind as it is. For Falco packages, we use the metadata model used by the [securityhub.dev](https://github.com/falcosecurity/cloud-native-security-hub), which allows multiple metadata files for different packages to live in the same folder. This doesn't play nicely with having multiple package versions or deploying an `artifacthub-pkg.yaml` file in the package version directory. At some point I think we should use our metadata file for Falco packages as we do for OPA, and have a specialized tracker for the Security Hub to not lose their content.
- **OLM**: it fits nicely, but it's not really needed for the use cases defined above, as almost all of them are already solved (except the install block IIRC).
- **Helm**: this is the package kind that would benefit the more of this change. However, during our last meeting it was mentioned that the Helm team was open to define some conventions for annotations in the `Chart.yaml` file, potentially even using an `artifacthub.io` prefix, that would help solving most of these limitations.

So given that mostly only Helm packages will benefit from this, and that there is an alternative solution that may be simpler, less confusing for users and less error prone, I'm not sure if we should move forward with this.

What do you think @DirtyCajunRice @mattfarina @scottrigby?

**Comment by DirtyCajunRice** [comment]
@tegioz From my years in the industry, I live by the statement
> A promise is not a delivery

Because of that, and the nature of helm's stability, I personally would like for this to move forward for helm and just notate in the pkg example which are ignored by helm (or which are allowed; whatever is a lesser number). Once Helm allows annotations in stable; you could deprecate for a minor version or 2.

Just my 2c

Thanks for your work on this!

**Comment by DirtyCajunRice** [comment]
Initially made the comment inline. Deleted and reposting here.

https://github.com/artifacthub/hub/blob/181027ab7c6516cdef327bcc6c23e489b9e5973d/internal/pkg/metadata.go#L26-L28

Appending without enrichment of existing would only cause people to want to leave out links from the Chart.yaml directly. I dont believe that is the intent though. Could a bit of extra logic exist that can enrich existing chart links and fall back to appending?

Example:
```go
if md.Links != nil {
	for i, mdLink := range md.Links {
		for _, pLink := range p.Links {
			if pLink.URL == mdLink.URL {
				p.Links[i].Name = mdLink.Name
				break
			}
		}
		p.Links = append(p.Links, mdLink)
	}
}
```

The same could be done for maintainer but only for the addition of a `Maintainer.URL` field that is a Chart.yaml option but not a `Maintainer` option currently. Proposal is that it, if exists, replaces the default `mailto:` link in the UI. I have other opinions about name vs vcs name but the arguments have all already been stated here https://github.com/helm/chart-testing/issues/192 :smile:

**Comment by tegioz** [comment]
The `EnrichPackageFromMetadata` function is not complete, the "mostly ready" was because of it precisely :) When I was going to start working on it I thought it'd better to stop and open this discussion, as I wasn't even sure what fields we'd like to be able to override in the case we finally wanted to do it. I just added a few fields as examples to not leave it empty (didn't test it either). So please don't take anything on that commit as final ;)

**Comment by tegioz** [comment]
> @tegioz From my years in the industry, I live by the statement
> 
> > A promise is not a delivery
> 
> Because of that, and the nature of helm's stability, I personally would like for this to move forward for helm and just notate in the pkg example which are ignored by helm (or which are allowed; whatever is a lesser number). Once Helm allows annotations in stable; you could deprecate for a minor version or 2.

I understand what you mean. But isn't Helm 3 already `stable`? 2.x appears as legacy in the Helm docs (I think since August, but don't trust me on this one).

I don't see why this would have to be delayed too much. As soon as the keys for the annotations are defined, which should be quick, I'll add support for it in the tracker, it won't take long. You wouldn't even have to wait until they are added to the Helm docs to start using them @DirtyCajunRice ;)

**Comment by tegioz** [comment]
Maybe we can start with the `operator` and `links` fields. We could use the following keys for them (using the prefix @mattfarina suggested in Slack the other day):

- artifacthub.io/operator
- artifacthub.io/links

For values containing lists or objects, we could embed them as strings:

```yaml
annotations:
  "artifacthub.io/operator": true
  "artifacthub.io/links": |
    - name: link1
      url: https://link1.url
    - name: link2
      url: https://link2.url
```

These annotations are meant to be interpreted by other applications, not Helm, so this probably should be documented somehow in Artifact Hub.

**Comment by tegioz** [comment]
I've just created a PR (https://github.com/artifacthub/hub/pull/646) implementing what I described in my previous comment.

Happy to merge (or adapt) it as soon as we agree on the annotations keys and format :)

CC: @mattfarina @scottrigby

**Comment by tegioz** [comment]
I can also add support to enrich maintainers info in this PR if you'd like, not a problem.

**Comment by scottrigby** [comment]
Hey @tegioz sorry for the delay on this. A few thoughts:

### Artifact Hub metadata in Chart.yaml or separate file?

Unlike a separate artifacthub metadata file, adding to `Chart.yaml` ties Artifact Hub metadata to a chart version. Since chart version packages are immutable, the only way to change this metadata is to release a new version. This is fine for the operator flag, since faceted search is for the current not previous versions. Right?

But for package display override (like enriching maintainers list) is the idea for Artifact Hub to only make the overrides for the package version whose Chart.yaml file that holds this info, or apply overrides from the current version to when users browse previous versions as well? Some pros and cons for this come to mind:
- Only overriding display per version that contains annotations is less likely to accidentally override lists chat change from version to version (example: `maintainers`, since it's not a map and the index is likely to periodically change per chart version)
- Also, if both lists are in the same file for the same version (as opposed to a separate Artifact Hub metadata file), accidental overrides are much less likely
- No ability to override previous versions (unless we use the current version annotations to override all previous ones. But as mentioned just above, that is likely to go wrong for lists because the index order is likely to change)

Install blocks may be tricky in this way. Helm repos may update things that require changing the install block for not only current but also past versions as well (such as when Bitnami changed the chart repo URL). Tying this info to an immutable package version's `Chart.yaml` file means we can't modify previous install block info with by releasing a new version with updated info. But maybe this is an OK trade-off, given that this is already the case with older install instructions inside previous package version READMEs?

### If the metadata should live in Chart.yaml, annotations are 👍 

I was originally in favor of additional fields in `Chart.yaml`, but after @mattfarina suggested the `annotations` field on in Tuesday's meeting I immediately agree – adding external application-specific functionality (in this case for Artifact Hub) is a perfect use case.

Regarding this:

>>> A promise is not a delivery  
>>>
>> Once Helm allows annotations in stable  
>>
> But isn't Helm 3 already stable?

Yes annotations are stable in Helm https://helm.sh/docs/topics/charts/#the-chartyaml-file.

Just wanted to note the above thoughts. If all of that seems OK, yes let's standardize annotations from the artifacthub side and document them as part of the same PR? The examples in https://github.com/artifacthub/hub/issues/634#issuecomment-690896405 seem clear to me: 
- `artifacthub.io/operator` bool
-  `artifacthub.io/links` string (YAML string literal expected to be in list format. Overrides index of `maintainers` field list item)
- `artifacthub.io/install-block` string (YAML string literal. Strict expected format?)

**Comment by tegioz** [comment]
Thanks for your input @scottrigby, you raise very good points :)

> Hey @tegioz sorry for the delay on this. A few thoughts:
> 
> ### Artifact Hub metadata in Chart.yaml or separate file?

In my lasts comments I meant in Chart.yml, sorry for not making that clear.

> Unlike a separate artifacthub metadata file, adding to `Chart.yaml` ties Artifact Hub metadata to a chart version. Since chart version packages are immutable, the only way to change this metadata is to release a new version. This is fine for the operator flag, since faceted search is for the current not previous versions. Right?

Yes, that's right. Actually, this applies as well to maintainers. 

Let me explain a bit more: packages as entities may have a number of maintainers. A package may also have multiple snapshots. Each version is a snapshot actually. But snapshots don't have maintainers. The reasoning behind this is that over time teams in organizations evolve, and the current people taking care of a package will probably have to take care of previous versions as well. If someone had an issue with an old version of a package, we thought that sending an email to someone that may not be even working on that anymore (even if it did at some point) wouldn't make much sense.

Just a a side note, as it may not be a problem if we don't go that way, but I was thinking that each chart version would have an `artifacthub-pkg.yaml` file inside the chart package. But let's not worry about this as it doesn't matter in this case.

> 
> But for package display override (like enriching maintainers list) is the idea for Artifact Hub to only make the overrides for the package version whose Chart.yaml file that holds this info, or apply overrides from the current version to when users browse previous versions as well? Some pros and cons for this come to mind:

This is related to my previous comment. That will depend on how that particular field is treated in Artifact Hub. The `operator flag` is a package level concept, independent of versions and only updated when it's updated in the last version. The same applies for `maintainers`. However, `links` is a snapshot concept, and it'll be updated for the corresponding version. 

> 
> * Only overriding display per version that contains annotations is less likely to accidentally override lists chat change from version to version (example: `maintainers`, since it's not a map and the index is likely to periodically change per chart version)
> * Also, if both lists are in the same file for the same version (as opposed to a separate Artifact Hub metadata file), accidental overrides are much less likely
> * No ability to override previous versions (unless we use the current version annotations to override all previous ones. But as mentioned just above, that is likely to go wrong for lists because the index order is likely to change)

For links, we are handling the list as if it was a map keyed by the url, updating the name (which is not available in the Chart.yaml sources list) when needed. We can do the same for maintainers based on the email field.

> 
> Install blocks may be tricky in this way. Helm repos may update things that require changing the install block for not only current but also past versions as well (such as when Bitnami changed the chart repo URL). Tying this info to an immutable package version's `Chart.yaml` file means we can't modify previous install block info with by releasing a new version with updated info. But maybe this is an OK trade-off, given that this is already the case with older install instructions inside previous package version READMEs?

Yes, this one is a bit tricky and it's something I added to the `artifacthub-pkg.yaml` thinking of OPA polices, for which we didn't have a standard installation mechanism. But I haven't included it in this PR, we can discuss that later on if it makes sense.

> 
> ### If the metadata should live in Chart.yaml, annotations are 👍

Cool :)

> I was originally in favor of additional fields in `Chart.yaml`, but after @mattfarina suggested the `annotations` field on in Tuesday's meeting I immediately agree – adding external application-specific functionality (in this case for Artifact Hub) is a perfect use case.
> 
> Regarding this:
> 
> > > > A promise is not a delivery
> > > 
> > > 
> > > Once Helm allows annotations in stable
> > 
> > 
> > But isn't Helm 3 already stable?
> 
> Yes annotations are stable in Helm https://helm.sh/docs/topics/charts/#the-chartyaml-file.
> 
> Just wanted to note the above thoughts. If all of that seems OK, yes let's standardize annotations from the artifacthub side and document them as part of the same PR? The examples in [#634 (comment)](https://github.com/artifacthub/hub/issues/634#issuecomment-690896405) seem clear to me:
> 
> * `artifacthub.io/operator` bool
> * `artifacthub.io/links` string (YAML string literal expected to be in list format. Overrides index of `maintainers` field list item)
> * `artifacthub.io/install-block` string (YAML string literal)
>   
>   * **question:** should we enforce an expected format, or render whatever (plain text) info might be added in here?

I think we should think carefully about this install block and not add it as part of this.

If we want to include the maintainers, we could also have **artifacthub.io/maintainers**, which would work similarly to the links field.

Thanks again!

**Comment by scottrigby** [comment]
Makes sense.

I agree the install block could get hairy. Some charts have complex steps, so that block could become unwieldy. This is what the README is for anyway.

Right thanks, I actually did mean to add `artifacthub.io/maintainers` but mixed the maintainers comments into `artifacthub.io/links` instead. But you get the idea 🙂

Keying off the email (for maintainers) and URL (for links) would make sense for changing the display link/names.

Fun question that's nagging my mind: is the only reason to override maintainers so that users can keep their source control (example GitHub) username in `maintainers[].name`, but then display a human-readable name in Artifact Hub? Would it make more sense to encourage users to add an additional, optional property like `maintainers[].display-name`, so no artifact hub-specific override is needed there?

Since helm specifies an optional `maintainers[].url` field, artifact hub can already link there as opposed to email of set (maybe this is already done? I have not checked).

What I'm wondering is if we're encouraging unneeded duplication by using annotations for everything.

Specifying links is another matter. The `sources` field is a simple list, and so not easy to customize using the built in property. This seems important for a few things, including defining the chart source code, where to contribute, etc.

**Comment by scottrigby** [comment]
Never mind this comment:
> Fun question that's nagging my mind: is the only reason to override maintainers so that users can keep their source control (example GitHub) username in maintainers[].name, but then display a human-readable name in Artifact Hub? Would it make more sense to encourage users to add an additional, optional property like maintainers[].display-name, so no artifact hub-specific override is needed there?

A defined annotation is best because we can document what's expected 👍

**Comment by tegioz** [comment]
> Since helm specifies an optional `maintainers[].url` field, artifact hub can already link there as opposed to email of set (maybe this is already done? I have not checked).

I haven't added support for the maintainers field yet, this it not done. It'd be great if there was a display name field in the maintainers object, but I understand it may not be that easy to make changes in Helm. If this is an option, we can leave it out though.

> What I'm wondering is if we're encouraging unneeded duplication by using annotations for everything.

Somehow it may look like that, yes. But at the same time we are improving how Helm packages are displayed in Artifact Hub, solving a real problem for some users, using something like annotations that seems to be created for situations like this :)

**Comment by scottrigby** [comment]
💯 % agree

PS, if we wanted, users can already add additional fields (display name or whatever) the maintainers []map, or other fields in Chart.yaml as long a they are of the correct type. From docs on [The Chart.yaml File](https://helm.sh/docs/topics/charts/#the-chartyaml-file) (and you can also validate it's fine with `helm lint`):
> Other fields will be silently ignored

However just after I mentioned it, I think `artifacthub` namespaced annotations as we discussed are actually better, because their purpose is clear, and Artifact Hub can document them properly.

That said, if there were wider value for adding additional (optional) fields to the Chart.yaml spec, the applicable ones could potentially move upstream into the Helm Chart API. A display name maybe is a good potential example of this? But anyway, annotations to start sound like the way forward here 👍 👍

**Comment by tegioz** [comment]
Awesome, thanks @scottrigby!
