### ISSUE TITLE
Can't resend verification link

### ISSUE THREAD

**Issue by sbaier1** [artifacthub/hub#831]
After signing up, we failed to acknowledge the verification link in time, which now expired.
However, there seems to be no mechanism to generate / send a new verification link.

How can we proceed here?

**Comment by tegioz** [comment]
Hi @sbaier1 

If the verification code has expired, you should be able to sign up again using the same username / email you used in the first place. Unfortunately this is not working as expected at the moment because of a bug in the user alias availability check, which I think I've just fixed.

I'll deploy this in ~20 minutes. I'll let you know when it's done so that you can give it a try when you have a chance.

Thanks.-

**Comment by tegioz** [comment]
Deployed @sbaier1. Please let me know if you find any issue signing up again.

**Comment by sbaier1** [comment]
that was fast 👍  sign-up worked fine this time, thank you.
