### ISSUE TITLE
Support CVE Whitelisting or Disable

### ISSUE THREAD

**Issue by cdjohnson** [artifacthub/hub#856]
I've just added a few Operator Lifecycle Manager (OLM) catalogs.  Nearly all of them use the Red Hat Universal Base Image 8 (ubi8 or ubi8-minimal) base image, which Red Hat considers safe and gives it a security vulnerability grade of A.

When the image scanner (looks to be Aquasecurity Trivy) scans these images it detects CVE-2019-5827 with sqllite-libs.

I'm guessing that Red Has decided to white-list this CVE in their own tool, possibly because chromium isn't included with the ubi8-minimal images, though I'm verifying.

It seems that it may be appropriate that an Operator may deem the vulnerability as a lower severity because of the context in which the image is being used.  These scanners do not, for example, consider the Pod's security context.

Or:  Provide the ability to DISABLE security scanning for select operators or catalogs.

**Comment by tegioz** [comment]
Containers images in OLM packages can now be whitelisted using the [`artifacthub.io/imagesWhitelist` annotation](https://github.com/artifacthub/hub/blob/master/docs/olm_annotations.md). Whitelisted images won't be scanned for security vulnerabilities.

This feature is also supported in Helm and OPA packages, although they rely on the existing `artifacthub.io/images` annotation that now has an extra boolean field named `whitelisted`.

**Comment by cdjohnson** [comment]
An Operator has multiple CSVs (one per version).  Right now the bundle/catalog formats don't have a way of describing a "Package".  There are features coming in OLM that will enable this in the future.

So, which CSV would you use the annotations from?  Just CSV from the Head of the Default Channel?

I think it would be useful to be able to decorate an Operator independently (some other meta data file) rather than updating the CSV directly.  Especially for those operators that we cannot modify the CSV for, yet we on the Catalog for.

My request:  Provide an option on the Catalog Repository to disable scanning for all operators in that catalog.  Or for specifically named packages or images in the catalog.

Since we may not own the CSV, or the base image for All CSVs may be affected, it may not be possible to add artifacthub.io specific annotations to the HEAD CSV.

**Comment by tegioz** [comment]
We use the CSV of each of the package's versions, as each version is scanned for security vulnerabilities. That way, when users switch from version to version in the package view, they can inspect the security reports of each of them. I think this provides maximum flexibility as it's possible to whitelist images per version if needed.

Internally in Artifact Hub, each package (can be an operator, or something else) may have one or more versions, called snapshots. We track the containers images used by each of those snapshots independently, including now if they've been whitelisted or not for that particular version. We do it this way because, over time, a package may change the images it uses and the ones it'd like to whitelist.
 
Said that, I think it makes sense to provide a switch at the repository level that disables scanning for all packages.

**Comment by tegioz** [comment]
#929 has just been deployed @cdjohnson. You can now disable scanning at the repository level editing the repository from the control panel.

**Comment by cdjohnson** [comment]
This works great.  Thank you!

**Comment by tegioz** [comment]
Awesome, no worries 👍🏻
