### ISSUE TITLE
Official badge for Nutanix Helm charts

### ISSUE THREAD

**Issue by tuxtof** [artifacthub/hub#969]
Hello,

As we've added the [artifacthub-repo.yml](https://github.com/nutanix/helm/blob/gh-pages/artifacthub-repo.yml) , we would like to have the Official badge on all Helm charts hosted in this repository:

https://artifacthub.io/packages/search?page=1&repo=nutanix

Best,
Christophe

**Comment by tegioz** [comment]
Hi @tuxtof

Done!

Could you please add a readme file for the [karbon-metric-server](https://artifacthub.io/packages/helm/nutanix/karbon-metric-server) package? The requirements for the official status are not properly documented yet, but I guess one of the points will be that the package provides some documentation.

Whereas the official status of the [nutanix-csi-storage](https://artifacthub.io/packages/helm/nutanix/nutanix-csi-storage) package seems clear to me, I'm not really sure if the `karbon-metric-server` should be marked as official too. The name and the description define well that this chart is for Nutanix Karbon, but it seems to be a chart to deploy [metrics-server](https://github.com/kubernetes-sigs/metrics-server) from Kubernetes Sigs. According to the definition of `official` we have in `artifacthub.io`, this status indicates that the publisher **owns** the software deployed by the package. This doesn't seem to be the case here though. The problem with this is that there are other alternative packages in `artifacthub.io` to deploy `metrics-server`, like the one from [Bitnami](https://artifacthub.io/packages/helm/bitnami/metrics-server) or the one from [olemarkus](https://artifacthub.io/packages/helm/metrics-server/metrics-server), both with several stars. Marking this package as official will position yours better in search results and might mislead users when making a decision about which one to use.

What do you think @tuxtof? Does this make sense? I understand this is not documented yet and it may be hard to draw the line to decide what is official and what not in some cases.

Please note that this issue is not exclusive of your repository. The [prometheus-kafka-exporter](https://artifacthub.io/packages/helm/prometheus-community/prometheus-kafka-exporter) package, for example, is marked as official as well and strictly speaking it presents the same issue somehow. It seems to be deploying a kafka exporter that isn't really owned by Prometheus (https://github.com/danielqsj/kafka_exporter). The owner of the software also provides a Helm chart (https://github.com/danielqsj/kafka_exporter/tree/master/charts/kafka-exporter, the "really official one" according to the definition? 😅), which makes the problem even more complicated. But on the other side, the exporter is for Prometheus and it also seems that the fact that it is maintained and provided by the Prometheus community is a strong incentive for users to actually use that package instead of other alternatives. And in the end, this is what this feature is all about, to facilitate users making the best decision when selecting what package to use.

Hopefully when this process is documented everything will be clearer and it'll be easier to make the decision of what is marked as official and what not 🙂

Do you have any thoughts on this @mattfarina @scottrigby?

Related to #542

**Comment by tuxtof** [comment]
Hi @tegioz 

First, thanks for your action and i just ask to the dev in charge of the karbon-metric-server chart to add a readme file

but you rise a very interesting question

first let me explain you what is this package

Nutanix Karbon is our CNCF certified k8s managed distribution on top of our enterprise cloud platform
Nutanix Karbon was not deployed out of the box with the metric server 
metric server need some specific configuration to be deployed on Nutanix Karbon due to some of our security choice
that's why we propose this specific helm chart to help customer deploying metric-server on nutanix karbon

so if we come back to the question

the chart/install method is official from nutanix but clearly not the metric-server himself

the goal is clearly not to be better positioned for this package because it is only for Nutanix karbon user
so i will understood if you remove the official badge from this one

i think it is a good rule to mark a package official only if the user/org who provide is the same than the one who maintain the software  deployed by the package.

Take care

**Comment by tegioz** [comment]
Thanks for your explanation @tuxtof, that makes sense 👍
