### ISSUE TITLE
The "-beta" tag appears as default in ArtifactHub UI

### ISSUE THREAD

**Issue by datamattsson** [artifacthub/hub#973]
![image](https://user-images.githubusercontent.com/7026024/102114916-a2a2fa00-3def-11eb-84ed-8b4260fadc62.png)

Helm CLI does the right thing and installs 1.3.0 when omitting version. Ideally, the UI should reflect what the CLI does.

**Comment by tegioz** [comment]
Hi @datamattsson 

The Helm CLI skips pre-release versions when using both search and install commands unless the `-devel` flag is provided.

Artifact Hub, at the moment, is not skipping pre-release versions. Each package has a `latest version` field that points to the most recent version available, regardless of whether it is a pre-release or not. This latest version is the one used by Artifact Hub for all operations by default unless a specific version is requested by the user.

In your example, it is `1.4.0-beta`:

<img width="1980" src="https://user-images.githubusercontent.com/1213902/102194822-0a277b00-3ebe-11eb-824b-e6ed4cc19620.png">

The reason we need to pick a version is that all metadata displayed in the UI corresponds to a specific version: the README file, keywords, maintainers, images, etc. And when the users switches the version, we reload the view with the appropriate data.

Whereas users can easily see the version currently used and they can switch to a different one in the UI, I understand that using the latest one available may mislead users to install a non stable version in some cases if they don't realize which one is selected.

We can change how this works, but it will have some implications beyond the install instructions displayed on the UI that I think are worth discussing.

- There are packages that may be using the semver pre-release identifier in what it seems to be non pre-release versions. Some examples: https://artifacthub.io/packages/helm/wso2/ob-pattern-1, https://artifacthub.io/packages/olm/community-operators/robin-operator, https://artifacthub.io/packages/helm/authentik/authentik or https://artifacthub.io/packages/helm/banzaicloud-stable/kubefed. In the latter the publisher recommends using `-devel` in the installation instructions as otherwise an old version would be picked up by the Helm CLI by default. There are more and some only have pre-release versions. Others use `-stable` as a pre-release identifier. We'll need to be careful to not break existing packages and document the criteria chosen so that the behavior can be understood by publishers and users.

<img width="1994" src="https://user-images.githubusercontent.com/1213902/102203263-a8204300-3ec8-11eb-89bb-3a2ed7c85cd3.png">

- Search results consistency: only the latest version's metadata is indexed to power searches. Other versions' metadata is stored and served only when the specific version is requested. This means that the criteria used to pick the `recommended version to install`, whether if it is the latest non pre-release or something else, should be applied early in the pipeline, not only in the UI, as that version's data is what should be displayed on search results.

- In addition to Helm packages, we support other kinds at the moment and there will be more, which may rely on tools using a different criteria. Should a change like this be applied across all kinds or have one specific per kind?

I haven't thought this thoroughly yet so I'm probably leaving some things out.

Personally, I like the concept of channels used in operators, and maybe something like that could be leveraged in Artifact Hub to allow publishers specify which package version do they recommend users to install. That could provide a lot of flexibility and it's something we already support for OLM operators. In your example, you could have two channels defined, `stable` and `beta`, with stable being the default one, and you could point each of them to the version you prefer regardless of the convention used on it.

But I'm happy to go either way 🙂 Looking forward to hearing more thoughts.

CC: @mattfarina @scottrigby

**Comment by datamattsson** [comment]
Thank you for the elaborate explanation. It helps. We are mainly concerned about our user experiences by filing this issue. Our process is currently to push a beta chart weeks/months before the actual release. Users on the Helm CLI won't be affected by our development work but on the other hand we keep directing users to ArtifactHub to learn about the Helm chart. We absolutely don't want users to accidentally install the beta chart as it might not even work and there's no support.

In an ideal world we would like the default landing on ArtifactHub reflect what `helm install` represent without any version flags. That includes omitting `--version 1.3.0` (in our case) in the "Helm Install" button on ArtifactHub. Browsing the different versions is certainly a nice feature though.

**Comment by tegioz** [comment]
Your use case makes sense, we need to improve that.

Even if we didn't have to find a solution for the pre-release identifiers and you were only releasing stable versions, omitting the version in the install instructions could lead to problems. In the end, everything we display in the package view corresponds to a specific version. There will always be a bit of delay between the reality your source repository represents and what Artifact Hub has been able to index, as they are different systems that should be in sync eventually.

At the moment, if everything is operating normally, that can be up to 30 mins. But imagine that for any reason the process tracking repositories fails and remains stopped for some more time, or there is a problem only with a specific repo and it can't be tracked until we realize there is a problem and fix it. The package view might be displaying the documentation and details of a past version, `1.2.3` for example, and  when the users proceed with the installation without specifying a version, they'd install `2.0.0` that was recently released.

This doesn't necessarily need to be a problem, it may be in some cases and not in others, but it's another point we should keep in mind when deciding how this should work.

Let's see what others think about this 🙂 

Thanks!

**Comment by tegioz** [comment]
We've just committed a new feature that another user requested for a different use case, that could help with yours as well as a temporary solution.

It's now possible to ask Artifact Hub to ignore certain packages / versions. The [configuration](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) allows using a regular expression to match specific versions.

So adding something like this to your repository metadata file would allow you to exclude beta versions from Artifact Hub, which effectively would point users to the latest stable one:

```yaml
ignore:
  - name: hpe-csi-driver
    version: beta
```

This feature will be probably deployed later on today. Please note that repositories are not processed again unless something has changed on them since the last time they were processed.

**Comment by tegioz** [comment]
We are also planning to work soon on a feature that will allow publishers to mark specific packages versions as `pre-release` (#977). The UI will display a label in the versions list and probably a warning in the installation modal to remind users that that version is not ready for production use. This could be an alternative solution to the one I mentioned in my previous comment.

**Comment by datamattsson** [comment]
Thanks @tegioz! This gives us more to work with and thanks for highlighting this little caveat:

> The package view might be displaying the documentation and details of a past version, 1.2.3 for example, and when the users proceed with the installation without specifying a version, they'd install 2.0.0 that was recently released.

We positively want to include version in the artifacthub presentation.

We'll discuss this internally but the beta version exclusion is probably what we want for now.

**Comment by tegioz** [comment]
The new `pre-release` status feature is ready and it has been deployed. It can be controlled using the [artifacthub.io/prerelease annotation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations).

**Comment by tegioz** [comment]
Hi @datamattsson 

I think we can close this one for now. The `ignore` field in the repository metadata file in combination with the `pre-release` flag at the package level should be of help customizing which versions appear in Artifact Hub. Please feel free to re-open if need.
